
import { Author, MethodologyType, Resource, Course } from './types';

export const UI_TRANSLATIONS: Record<string, any> = {
  no: {
    navDashboard: 'Dashboard',
    navProfile: 'Sjelssenter',
    navAstrology: 'Astrologi',
    navNumerology: 'Numerologi',
    navTarot: 'Tarot',
    navHoroscope: 'Horoskop',
    navChineseAstrology: 'Kinesisk',
    navSettings: 'Innstillinger',
    navLogout: 'Logg ut',
    welcomeBack: 'Velkommen tilbake til arkivene',
    soulOverview: 'Sjelens Oversikt',
    dailyEnergy: 'Dagens Energi',
    emotionalWave: 'Følelsesmessig Bølge',
    cosmicWeather: 'Kosmisk Vær',
    startJourney: 'Start Min Kronike',
    natalTitle: 'Ditt Opprinnelige Kart',
    relocationTitle: 'Flytting',
    transitTitle: 'Transitter',
    vedicTitle: 'Vedic',
    esotericTitle: 'Esoterisk',
    classicalTitle: 'Klassisk',
    modernTitle: 'Moderne',
    writeBook: 'Skriv Min Livsbok',
    archiveReport: 'Arkiver Rapport',
    printReport: 'Skriv ut Rapport',
    languageName: 'Norsk',
    periodDay: 'I dag',
    periodWeek: 'Denne uken',
    periodMonth: 'Denne måneden',
    periodYear: 'Hele året',
    horoscopeTitle: 'Ditt Personlige Horoskop',
    horoscopeSubtitle: 'Basert på sjelens transitter',
    chineseTitle: 'Kinesisk Horoskop',
    chineseSubtitle: 'De fire søyler og elementenes balanse',
    traditionLabel: 'Tradisjon',
    analysisLabel: 'Analyse',
    saveProfileBtn: 'Oppdater Sjelsprofil',
    saveSuccess: 'Data er trygt arkivert i din sjelsprofil',
    nameLabel: 'Navn for Vibrasjon',
    birthDateLabel: 'Fødselsdato',
    birthTimeLabel: 'Klokkeslett',
    birthLocationLabel: 'Fødested',
    houseSystemLabel: 'Foretrukket Hussystem',
    apiKeysTitle: 'Personlige Arkivnøkler',
    apiKeysDesc: 'Disse nøklene brukes for å åpne de dype AI-analysene.',
    appearanceTitle: 'App-utseende',
    lightMode: 'Lys',
    darkMode: 'Mørk',
    archiveTitle: 'Mine Lagrede Innsikter',
    noArchiveDesc: 'Ditt arkiv venter på sin første historie...',
    readInsight: 'Les Innsikt',
    backToArchive: 'Tilbake til Arkivet',
    technicalInventory: 'Teknisk Inventar',
    transformationCycles: 'Transformasjon & Sykluser',
    powerMantraLabel: 'Ditt Makt-Mantra',
    numerology: {
      soulMapTitle: 'Sjelens Fullstendige Tallkart',
      cyclesTitle: 'Tidens Hjul & Utfordringer',
      karmaAlert: 'Karmisk Gjeld Detektert',
      coreFour: 'De Fire Kjernevibrasjoner'
    },
    landing: {
      heroTitle: 'Din Sjels',
      heroSubtitle: 'Kronike',
      heroDesc: 'Gå forbi overfladiske horoskop. Astro Mason dechiffrerer din sjel gjennom esoterisk astrologi, dyp tarot og hellig numerologi.',
      startBtn: 'Start Reisen',
      createArchive: 'Opprett ditt Arkiv',
      login: 'Logg inn',
      investmentTitle: 'Sjelelig Investering',
      investmentDesc: 'Velg din vei til selvinnsikt',
      singleTitle: 'Enkeltreise',
      singlePrice: '€14',
      singleUnit: '/ rapport',
      singleDesc: 'Perfekt for et dypdykk i din nåværende situasjon eller et spesifikt spørsmål.',
      singleFeatures: ['Komplett "Livsbok" (4000+ ord)', 'Dyp personlig analyse', 'Evig tilgang til rapport'],
      masterTitle: 'Mester-medlemskap',
      masterPrice: '€49',
      masterUnit: '/ år',
      masterDesc: 'Full og ubegrenset tilgang til alle arkiver, tarot-legg og numerologiske koder.',
      masterFeatures: ['Ubegrenset Astro-rapporter', 'Full tilgang til Tarot-modul', 'Alle numerologiske koder', 'Personlig innsiktshub'],
      bestValue: 'Beste Verdi',
      selectPlan: 'Velg denne',
      selectMaster: 'Velg Mester-veien',
      authTitleLogin: 'Velkommen Tilbake',
      authTitleReg: 'Opprett Sjelsprofil',
      authDesc: 'Gå inn i de dype arkivene',
      emailLabel: 'E-postadresse',
      passLabel: 'Passord',
      loginBtn: 'Logg inn',
      regBtn: 'Registrer Bruker',
      noAccount: 'Har du ikke konto?',
      hasAccount: 'Har du allerede konto?',
      clickHere: 'Klikk her'
    }
  },
  en: {
    navDashboard: 'Dashboard',
    navProfile: 'Soul Center',
    navAstrology: 'Astrology',
    navNumerology: 'Numerology',
    navTarot: 'Tarot',
    navHoroscope: 'Horoscope',
    navChineseAstrology: 'Chinese',
    navSettings: 'Settings',
    navLogout: 'Logout',
    welcomeBack: 'Welcome back to the archives',
    soulOverview: 'Soul Overview',
    dailyEnergy: 'Daily Energy',
    emotionalWave: 'Emotional Wave',
    cosmicWeather: 'Cosmic Weather',
    startJourney: 'Start My Chronicle',
    natalTitle: 'Your Natal Chart',
    relocationTitle: 'Relocation',
    transitTitle: 'Transits',
    vedicTitle: 'Vedic',
    esotericTitle: 'Esoteric',
    classicalTitle: 'Classical',
    modernTitle: 'Modern',
    writeBook: 'Write My Life Book',
    archiveReport: 'Archive Report',
    printReport: 'Print Report',
    languageName: 'English',
    periodDay: 'Today',
    periodWeek: 'This Week',
    periodMonth: 'This Month',
    periodYear: 'This Year',
    horoscopeTitle: 'Your Personal Horoscope',
    horoscopeSubtitle: 'Based on soul transits',
    chineseTitle: 'Chinese Horoscope',
    chineseSubtitle: 'The four pillars and balance of elements',
    traditionLabel: 'Tradition',
    analysisLabel: 'Analysis',
    saveProfileBtn: 'Update Soul Profile',
    saveSuccess: 'Data successfully archived in your soul profile',
    nameLabel: 'Name for Vibration',
    birthDateLabel: 'Birth Date',
    birthTimeLabel: 'Birth Time',
    birthLocationLabel: 'Birth Location',
    houseSystemLabel: 'Preferred House System',
    apiKeysTitle: 'Personal Archive Keys',
    apiKeysDesc: 'These keys are used to open deep AI analyses.',
    appearanceTitle: 'App Appearance',
    lightMode: 'Light',
    darkMode: 'Dark',
    archiveTitle: 'My Saved Insights',
    noArchiveDesc: 'Your archive awaits its first story...',
    readInsight: 'Read Insight',
    backToArchive: 'Back to Archive',
    technicalInventory: 'Technical Inventory',
    transformationCycles: 'Transformation & Cycles',
    powerMantraLabel: 'Your Power Mantra',
    numerology: {
      soulMapTitle: 'Complete Soul Map',
      cyclesTitle: 'Wheel of Time & Challenges',
      karmaAlert: 'Karmic Debt Detected',
      coreFour: 'The Core Four Vibrations'
    },
    landing: {
      heroTitle: 'Chronicle of',
      heroSubtitle: 'Your Soul',
      heroDesc: 'Go beyond shallow horoscopes. Astro Mason deciphers your soul through esoteric astrology, deep tarot, and sacred numerology.',
      startBtn: 'Start Journey',
      createArchive: 'Create Your Archive',
      login: 'Login',
      investmentTitle: 'Soul Investment',
      investmentDesc: 'Choose your path to self-insight',
      singleTitle: 'Single Journey',
      singlePrice: '€14',
      singleUnit: '/ report',
      singleDesc: 'Perfect for a deep dive into your current situation or a specific question.',
      singleFeatures: ['Complete "Life Book" (4000+ words)', 'Deep personal analysis', 'Lifetime access to report'],
      masterTitle: 'Master Membership',
      masterPrice: '€49',
      masterUnit: '/ year',
      masterDesc: 'Full and unlimited access to all archives, tarot spreads, and numerological codes.',
      masterFeatures: ['Unlimited Astro Reports', 'Full Tarot Module Access', 'All Numerological Codes', 'Personal Insight Hub'],
      bestValue: 'Best Value',
      selectPlan: 'Select Plan',
      selectMaster: 'Choose Master Path',
      authTitleLogin: 'Welcome Back',
      authTitleReg: 'Create Soul Profile',
      authDesc: 'Enter the deep archives',
      emailLabel: 'Email Address',
      passLabel: 'Password',
      loginBtn: 'Login',
      regBtn: 'Register',
      noAccount: 'No account?',
      hasAccount: 'Already have an account?',
      clickHere: 'Click here'
    }
  },
  fr: {
    navDashboard: 'Tableau de bord',
    navProfile: 'Centre de l\'Âme',
    navAstrology: 'Astrologie',
    navNumerology: 'Numérologie',
    navTarot: 'Tarot',
    navHoroscope: 'Horoscope',
    navChineseAstrology: 'Chinois',
    navSettings: 'Paramètres',
    navLogout: 'Déconnexion',
    welcomeBack: 'Bienvenue dans les archives',
    soulOverview: 'Aperçu de l\'Âme',
    dailyEnergy: 'Énergie du Jour',
    emotionalWave: 'Vague Émotionnelle',
    cosmicWeather: 'Météo Cosmique',
    startJourney: 'Démarrer ma Chronique',
    natalTitle: 'Votre Carte du Ciel',
    relocationTitle: 'Relocalisation',
    transitTitle: 'Transits',
    vedicTitle: 'Védique',
    esotericTitle: 'Ésotérique',
    classicalTitle: 'Classique',
    modernTitle: 'Moderne',
    writeBook: 'Écrire mon Livre de Vie',
    archiveReport: 'Archiver le Rapport',
    printReport: 'Imprimer le Rapport',
    languageName: 'Français',
    periodDay: 'Aujourd\'hui',
    periodWeek: 'Cette Semaine',
    periodMonth: 'Ce Mois',
    periodYear: 'Cette Année',
    horoscopeTitle: 'Votre Horoscope Personnel',
    horoscopeSubtitle: 'Basé sur les transits de l\'âme',
    chineseTitle: 'Horoscope Chinois',
    chineseSubtitle: 'Les quatre piliers et l\'équilibre des éléments',
    traditionLabel: 'Tradition',
    analysisLabel: 'Analyse',
    saveProfileBtn: 'Mettre à jour le Profil',
    saveSuccess: 'Données archivées avec succès',
    nameLabel: 'Nom de Vibration',
    birthDateLabel: 'Date de Naissance',
    birthTimeLabel: 'Heure de Naissance',
    birthLocationLabel: 'Lieu de Naissance',
    houseSystemLabel: 'Système de Maisons',
    apiKeysTitle: 'Clés d\'Archive',
    apiKeysDesc: 'Ces clés ouvrent les analyses IA profondes.',
    appearanceTitle: 'Apparence',
    lightMode: 'Clair',
    darkMode: 'Sombre',
    archiveTitle: 'Mes Aperçus Enregistrés',
    noArchiveDesc: 'Votre archive attend sa première histoire...',
    readInsight: 'Lire l\'Aperçu',
    backToArchive: 'Retour à l\'Archive',
    technicalInventory: 'Inventaire Technique',
    transformationCycles: 'Transformation & Cycles',
    powerMantraLabel: 'Votre Mantra de Pouvoir',
    landing: {
      heroTitle: 'Chronique de',
      heroSubtitle: 'Votre Âme',
      heroDesc: 'Allez au-delà des horoscopes superficiels. Astro Mason déchiffre votre âme par l\'astrologie ésotérique, le tarot profond et la numérologie sacrée.',
      startBtn: 'Commencer',
      createArchive: 'Créer votre Archive',
      login: 'Connexion',
      investmentTitle: 'Investissement Spirituel',
      investmentDesc: 'Choisissez votre voie',
      singleTitle: 'Voyage Unique',
      singlePrice: '14€',
      singleUnit: '/ rapport',
      singleDesc: 'Parfait pour approfondir votre situation actuelle.',
      singleFeatures: ['Livre de Vie complet (4000+ mots)', 'Analyse personnelle profonde', 'Accès illimité'],
      masterTitle: 'Membre Maître',
      masterPrice: '49€',
      masterUnit: '/ an',
      masterDesc: 'Accès illimité à toutes les archives, tirages et codes.',
      masterFeatures: ['Rapports Astro illimités', 'Accès total au Tarot', 'Tous les codes numérologiques', 'Hub d\'aperçus personnels'],
      bestValue: 'Meilleure Valeur',
      selectPlan: 'Choisir',
      selectMaster: 'Voie du Maître',
      authTitleLogin: 'Bon Retour',
      authTitleReg: 'Créer Profil',
      authDesc: 'Entrer dans les archives',
      emailLabel: 'E-mail',
      passLabel: 'Mot de passe',
      loginBtn: 'Se connecter',
      regBtn: 'S\'inscrire',
      noAccount: 'Pas de compte ?',
      hasAccount: 'Déjà inscrit ?',
      clickHere: 'Klikk her'
    }
  },
  de: {
    navDashboard: 'Dashboard',
    navProfile: 'Seelenzentrum',
    navAstrology: 'Astrologie',
    navNumerology: 'Numerologie',
    navTarot: 'Tarot',
    navHoroscope: 'Horoskop',
    navChineseAstrology: 'Chinesisch',
    navSettings: 'Einstellungen',
    navLogout: 'Abmelden',
    welcomeBack: 'Willkommen zurück im Archiv',
    soulOverview: 'Seelenübersicht',
    dailyEnergy: 'Tagesenergie',
    emotionalWave: 'Emotionale Welle',
    cosmicWeather: 'Kosmisches Wetter',
    startJourney: 'Meine Chronik starten',
    natalTitle: 'Ihr Geburtshoroskop',
    relocationTitle: 'Ortwechsel',
    transitTitle: 'Transite',
    vedicTitle: 'Vedisch',
    esotericTitle: 'Esoterisch',
    classicalTitle: 'Klassisch',
    modernTitle: 'Modern',
    writeBook: 'Mein Lebensbuch schreiben',
    archiveReport: 'Bericht archivieren',
    printReport: 'Bericht drucken',
    languageName: 'Deutsch',
    periodDay: 'Heute',
    periodWeek: 'Diese Woche',
    periodMonth: 'Diesen Monat',
    periodYear: 'Dieses Jahr',
    horoscopeTitle: 'Ihr persönliches Horoskop',
    horoscopeSubtitle: 'Basierend auf Seelentransiten',
    chineseTitle: 'Chinesisches Horoskop',
    chineseSubtitle: 'Die vier Säulen und Elemente',
    traditionLabel: 'Tradition',
    analysisLabel: 'Analyse',
    saveProfileBtn: 'Profil aktualisieren',
    saveSuccess: 'Daten erfolgreich im Seelenprofil archiviert',
    nameLabel: 'Name für Schwingung',
    birthDateLabel: 'Geburtsdatum',
    birthTimeLabel: 'Geburtszeit',
    birthLocationLabel: 'Geburtsort',
    houseSystemLabel: 'Häusersystem',
    apiKeysTitle: 'Archivschlüssel',
    apiKeysDesc: 'Diese Schlüssel öffnen tiefe KI-Analysen.',
    appearanceTitle: 'Erscheinungsbild',
    lightMode: 'Hell',
    darkMode: 'Dunkel',
    archiveTitle: 'Meine gespeicherten Einblicke',
    noArchiveDesc: 'Ihr Archiv wartet auf seine erste Geschichte...',
    readInsight: 'Einblick lesen',
    backToArchive: 'Zurück zum Archiv',
    technicalInventory: 'Technisches Inventar',
    transformationCycles: 'Transformation & Zyklen',
    powerMantraLabel: 'Ihr Kraft-Mantra',
    landing: {
      heroTitle: 'Chronik',
      heroSubtitle: 'Ihrer Seele',
      heroDesc: 'Gehen Sie über oberflächliche Horoskope hinaus. Astro Mason entschlüsselt Ihre Seele durch esoterische Astrologie, tiefes Tarot und heilige Numerologie.',
      startBtn: 'Reise beginnen',
      createArchive: 'Archiv erstellen',
      login: 'Login',
      investmentTitle: 'Seeleninvestition',
      investmentDesc: 'Wählen Sie Ihren Weg zur Selbsterkenntnis',
      singleTitle: 'Einzelreise',
      singlePrice: '14€',
      singleUnit: '/ Bericht',
      singleDesc: 'Perfekt für einen tiefen Einblick in Ihre aktuelle Situation.',
      singleFeatures: ['Vollständiges "Lebensbuch" (4000+ Wörter)', 'Tiefe persönliche Analyse', 'Ewiger Zugriff'],
      masterTitle: 'Master-Mitgliedschaft',
      masterPrice: '49€',
      masterUnit: '/ Jahr',
      masterDesc: 'Unbegrenzter Zugriff auf alle Archive, Tarot-Legungen und Codes.',
      masterFeatures: ['Unbegrenzte Berichte', 'Voller Tarot-Zugriff', 'Alle numerologischen Codes', 'Persönlicher Insight-Hub'],
      bestValue: 'Bester Wert',
      selectPlan: 'Plan wählen',
      selectMaster: 'Weg des Meisters',
      authTitleLogin: 'Willkommen zurück',
      authTitleReg: 'Profil erstellen',
      authDesc: 'Betreten Sie die tiefen Archive',
      emailLabel: 'E-Mail-Adresse',
      passLabel: 'Passord',
      loginBtn: 'Einloggen',
      regBtn: 'Registrieren',
      noAccount: 'Kein Konto?',
      hasAccount: 'Bereits ein Konto?',
      clickHere: 'Hier klicken'
    }
  },
  ru: {
    navDashboard: 'Панель',
    navProfile: 'Центр Души',
    navAstrology: 'Астрология',
    navNumerology: 'Нумерология',
    navTarot: 'Таро',
    navHoroscope: 'Гороскоп',
    navChineseAstrology: 'Китайский',
    navSettings: 'Настройки',
    navLogout: 'Выйти',
    welcomeBack: 'Добро пожаловать в архивы',
    soulOverview: 'Обзор Души',
    dailyEnergy: 'Энергия Дня',
    emotionalWave: 'Эмоциональная Волна',
    cosmicWeather: 'Космическая Погода',
    startJourney: 'Начать Хронику',
    natalTitle: 'Натальная Карта',
    relocationTitle: 'Релокация',
    transitTitle: 'Транзиты',
    vedicTitle: 'Ведическая',
    esotericTitle: 'Эзотерическая',
    classicalTitle: 'Классическая',
    modernTitle: 'Модерн',
    writeBook: 'Написать Книга Жизни',
    archiveReport: 'Архивировать Отчет',
    printReport: 'Печать Отчета',
    languageName: 'Русский',
    periodDay: 'Сегодня',
    periodWeek: 'Эта неделя',
    periodMonth: 'Этот месяц',
    periodYear: 'Этот год',
    horoscopeTitle: 'Личный Гороскоп',
    horoscopeSubtitle: 'На основе транзитов души',
    chineseTitle: 'Китайский Гороскоп',
    chineseSubtitle: 'Четыре столпа и баланс стихий',
    traditionLabel: 'Традиция',
    analysisLabel: 'Анализ',
    saveProfileBtn: 'Обновить Профиль',
    saveSuccess: 'Данные успешно заархивированы',
    nameLabel: 'Имя для вибрации',
    birthDateLabel: 'Дата рождения',
    birthTimeLabel: 'Время рождения',
    birthLocationLabel: 'Место рождения',
    houseSystemLabel: 'Система домов',
    apiKeysTitle: 'Ключи доступа',
    apiKeysDesc: 'Эти ключи открывают глубокий анализ ИИ.',
    appearanceTitle: 'Внешний вид',
    lightMode: 'Светлая',
    darkMode: 'Темная',
    archiveTitle: 'Сохраненные идеи',
    noArchiveDesc: 'Ваш архив ждет своей первой истории...',
    readInsight: 'Читать',
    backToArchive: 'Назад в Архив',
    technicalInventory: 'Технический Инвентарь',
    transformationCycles: 'Трансформация и Циклы',
    powerMantraLabel: 'Мантра Силы',
    landing: {
      heroTitle: 'Хроника',
      heroSubtitle: 'Вашей Души',
      heroDesc: 'За пределами поверхностных гороскопов. Astro Mason расшифровывает вашу душу через астрологию, таро и нумерологию.',
      startBtn: 'Начать Путь',
      createArchive: 'Создать Архив',
      login: 'Войти',
      investmentTitle: 'Инвестиция в себя',
      investmentDesc: 'Выберите свой путь к познанию',
      singleTitle: 'Разовый отчет',
      singlePrice: '14€',
      singleUnit: '/ отчет',
      singleDesc: 'Идеально для глубокого погружения в текущую ситуацию.',
      singleFeatures: ['Полная "Книга Жизни" (4000+ слов)', 'Глубокий личный анализ', 'Вечный доступ'],
      masterTitle: 'Мастер-подписка',
      masterPrice: '49€',
      masterUnit: '/ год',
      masterDesc: 'Полный и неограниченный доступ ко всем архивам и кодам.',
      masterFeatures: ['Безлимитные отчеты', 'Полный доступ к Таро', 'Все нумерологические коды', 'Личный хаб озарений'],
      bestValue: 'Лучший выбор',
      selectPlan: 'Выбрать',
      selectMaster: 'Путь Мастера',
      authTitleLogin: 'С возвращением',
      authTitleReg: 'Создать профиль',
      authDesc: 'Войти в глубокие архивы',
      emailLabel: 'E-mail адрес',
      passLabel: 'Пароль',
      loginBtn: 'Войти',
      regBtn: 'Регистрация',
      noAccount: 'Нет аккаунта?',
      hasAccount: 'Уже есть аккаунт?',
      clickHere: 'Нажмите сюда'
    }
  }
};

export const ASTRO_KNOWLEDGE_BASE: Record<string, string> = {
    'Væren': 'Keiseren (Struktur, lederskap, initiativ)',
    'Tyren': 'Hierofanten (Tradisjon, verdier, stabilitet)',
    'Tvillingene': 'De Elskende (Valg, dualitet, kommunikasjon)',
    'Krepsen': 'Vognen (Beskyttelse, vilje, emosjonell kontroll)',
    'Løven': 'Styrke (Indre kraft, mot, lidenskap)',
    'Jomfruen': 'Eneboeren (Analyse, introspeksjon, detaljer)',
    'Vekten': 'Rettferdighet (Balanse, karma, sannhet)',
    'Skorpionen': 'Døden (Transformasjon, slippe taket, fornyelse)',
    'Skytten': 'Måtehold (Syntese, visjon, høyere mening)',
    'Steinbukken': 'Djevelen (Materialisme, ambisjon, grenser)',
    'Vannmannen': 'Stjernen (Håp, humanitær visjon, fremtid)',
    'Fiskene': 'Månen (Illusjon, drømmer, underbevissthet)',
    'Ild': 'Inspirasjon, handling, vilje (Wands)',
    'Jord': 'Manifestasjon, krop, ressurser (Pentacles)',
    'Luft': 'Tanke, kommunikasjon, konflikt (Swords)',
    'Vann': 'Følelser, relasjoner, intuisjon (Cups)'
};

// Fixes for Library, Methodology, Courses, and Tarot components
export const METHODOLOGY_DESCRIPTIONS: Record<MethodologyType, string> = {
  [MethodologyType.WESTERN_CLASSICAL]: "Tradisjonell vestlig astrologi med fokus på essensielle verdigheter og hussystemer.",
  [MethodologyType.HELLENISTIC]: "Antikk gresk astrologi som gjenoppdaget teknikker som sekt og tidsherrer.",
  [MethodologyType.VEDIC]: "Indisk astrologi (Jyotish) basert på det sideriske dyrekretsen og nakshatras.",
  [MethodologyType.PSYCHOLOGICAL]: "Moderne tilnærming som bruker astrologi som et verktøy for selvutvikling og forståelse av psyken.",
  [MethodologyType.EVOLUTIONARY]: "Fokus på sjelens reise gjennom livstider, ofte med fokus på Pluto og månens noder.",
  [MethodologyType.ESOTERIC]: "Sjelens astrologi slik den er presentert av Alice Bailey, med fokus på sjelens formål.",
  [MethodologyType.SPECIALIZED]: "Spesialiserte teknikker som horær, eleksjonell eller medisinsk astrologi."
};

export const AUTHORS: Author[] = [
  {
    id: '1',
    name: 'Claudius Ptolemy',
    era: 'Ancient',
    specialty: 'Classical Foundations',
    description: 'Forfatter av Tetrabiblos, fundamentet for vestlig astrologi.',
    keyWorks: ['Tetrabiblos', 'Almagest'],
    methodologies: [MethodologyType.WESTERN_CLASSICAL]
  },
  {
    id: '2',
    name: 'Vettius Valens',
    era: 'Ancient',
    specialty: 'Hellenistic Techniques',
    description: 'En av de mest praktiske kildene for antikke astrologiske teknikker.',
    keyWorks: ['The Anthology'],
    methodologies: [MethodologyType.HELLENISTIC]
  },
  {
    id: '3',
    name: 'Alan Leo',
    era: 'Modern',
    specialty: 'Psychological Astrology',
    description: 'Ofte kalt faren til moderne astrologi.',
    keyWorks: ['Astrology for All'],
    methodologies: [MethodologyType.PSYCHOLOGICAL]
  }
];

export const RESOURCES: Resource[] = [
  {
    id: 'r1',
    title: 'Christian Astrology',
    author: 'William Lilly',
    type: 'Book',
    description: 'Den definitive guiden til horær astrologi.',
    isRecommended: true,
    link: 'https://archive.org'
  }
];

export const COURSES: Course[] = [
  {
    id: 'c1',
    title: 'Introduksjon til Klassisk Astrologi',
    description: 'Lær de grunnleggende prinsippene i vestlig tradisjon.',
    level: 'Beginner',
    duration: '10 timer',
    instructor: 'AstroMason',
    thumbnail: 'https://images.unsplash.com/photo-1532667449560-72a95c8d381b',
    progress: 0,
    isCertified: true,
    modules: []
  },
  {
    id: 'c2',
    title: 'Esoterisk Visdom',
    description: 'Utforsk sjelens vei gjennom stjernene.',
    level: 'Advanced',
    duration: '20 timer',
    instructor: 'AstroMason',
    thumbnail: 'https://images.unsplash.com/photo-1518133910546-b6c2fb7d79e3',
    progress: 0,
    isCertified: true,
    modules: []
  }
];

export const MAJOR_ARCANA = [
  { id: 0,  name: 'Narren',              img: 'https://upload.wikimedia.org/wikipedia/commons/9/90/RWS_Tarot_00_Fool.jpg',               keywords: ['Start', 'Uskyld', 'Risiko'], meaning: 'En ny reise, et sprang ut i det ukjente, uskyld og spontanitet. Reversert: Uansvarlighet, dumdristighet, naivitet.' },
  { id: 1,  name: 'Magikeren',           img: 'https://upload.wikimedia.org/wikipedia/commons/d/de/RWS_Tarot_01_Magician.jpg',           keywords: ['Manifestasjon', 'Kraft', 'Vilje'], meaning: 'Manifestasjon, viljestyrke, kreativitet, ressurser. Reversert: Manipulasjon, ubrukte talenter, lureri.' },
  { id: 2,  name: 'Yppersteprestinnen', img: 'https://upload.wikimedia.org/wikipedia/commons/8/88/RWS_Tarot_02_High_Priestess.jpg',     keywords: ['Intuisjon', 'Mysterier', 'Underbevissthet'], meaning: 'Intuisjon, underbevissthet, hemmeligheter, det ubevisste. Reversert: Undertrykte følelser, hemmeligheter, overfladiskhet.' },
  { id: 3,  name: 'Keiserinnen',         img: 'https://upload.wikimedia.org/wikipedia/commons/d/d2/RWS_Tarot_03_Empress.jpg',            keywords: ['Fruktbarhet', 'Natur', 'Overflod'], meaning: 'Fruktbarhet, omsorg, overflod, natur, skjønnhet. Reversert: Kreativ blokkering, avhengighet, stagnasjon.' },
  { id: 4,  name: 'Keiseren',            img: 'https://upload.wikimedia.org/wikipedia/commons/c/c3/RWS_Tarot_04_Emperor.jpg',            keywords: ['Autoritet', 'Struktur', 'Stabilitet'], meaning: 'Autoritet, struktur, kontroll, farsfigur, lederskap. Reversert: Tyranni, rigiditet, mangel på disiplin.' },
  { id: 5,  name: 'Ypperstepresten',     img: 'https://upload.wikimedia.org/wikipedia/commons/8/8d/RWS_Tarot_05_Hierophant.jpg',         keywords: ['Tradisjon', 'Spiritualitet', 'Veiledning'], meaning: 'Tradisjon, konformitet, veiledning, institusjoner. Reversert: Utfordring av tradisjoner, ukonvensjonell, frihet.' },
  { id: 6,  name: 'Elskerne',            img: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/TheLovers.jpg',                       keywords: ['Kjærlighet', 'Valg', 'Union'], meaning: 'Kjærlighet, harmoni, valg, relasjoner, forening. Reversert: Ubalanse, konflikt i relasjoner, dårlige valg.' },
  { id: 7,  name: 'Vognen',              img: 'https://upload.wikimedia.org/wikipedia/commons/9/9b/RWS_Tarot_07_Chariot.jpg',            keywords: ['Seier', 'Kontroll', 'Besluttsomhet'], meaning: 'Kontroll, viljestyrke, seier, selvsikkerhet, retning. Reversert: Mangel på retning, aggresjon, tap av kontroll.' },
  { id: 8,  name: 'Styrken',             img: 'https://upload.wikimedia.org/wikipedia/commons/f/f5/RWS_Tarot_08_Strength.jpg',           keywords: ['Mot', 'Tålmodighet', 'Indre kraft'], meaning: 'Indre styrke, mot, medfølelse, tålmodighet. Reversert: Svakhet, selv-tvil, mangel på selvkontroll.' },
  { id: 9,  name: 'Eremiten',            img: 'https://upload.wikimedia.org/wikipedia/commons/4/4d/RWS_Tarot_09_Hermit.jpg',             keywords: ['Introspeksjon', 'Søken', 'Visdom'], meaning: 'Introspeksjon, sjelelig søken, veiledning, ensomhet. Reversert: Isolasjon, ensomhet, tilbaketrekning.' },
  { id: 10, name: 'Lykkens Hjul',        img: 'https://upload.wikimedia.org/wikipedia/commons/3/3c/RWS_Tarot_10_Wheel_of_Fortune.jpg',   keywords: ['Syklus', 'Karma', 'Skjebne'], meaning: 'Skjebne, karma, vendepunkt, sykluser. Reversert: Uflaks, motstand mot endring, brudd på sykluser.' },
  { id: 11, name: 'Rettferdigheten',     img: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/RWS_Tarot_11_Justice.jpg',            keywords: ['Balanse', 'Sannhet', 'Årsak-virkning'], meaning: 'Rettferdighet, sannhet, årsak og virkning, karma, balanse. Reversert: Urettferdighet, ubalanse, uærlighet.' },
  { id: 12, name: 'Den Hengte',          img: 'https://upload.wikimedia.org/wikipedia/commons/2/2b/RWS_Tarot_12_Hanged_Man.jpg',         keywords: ['Overgivelse', 'Pause', 'Nytt perspektiv'], meaning: 'Nytt perspektiv, offer, pause, overgivelse. Reversert: Fastlåsthet, motstand mot endring, unødvendig offer.' },
  { id: 13, name: 'Døden',              img: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/RWS_Tarot_13_Death.jpg',              keywords: ['Transformasjon', 'Slutt', 'Ny begynnelse'], meaning: 'Slutten på en syklus, transformasjon, forandring, overgang. Reversert: Motstand mot forandring, stagnasjon, frykt for det ukjente.' },
  { id: 14, name: 'Temperansen',         img: 'https://upload.wikimedia.org/wikipedia/commons/f/f8/RWS_Tarot_14_Temperance.jpg',         keywords: ['Balanse', 'Moderasjon', 'Flyt'], meaning: 'Balanse, moderasjon, tålmodighet, formål, mening. Reversert: Ubalanse, ekstremisme, mangel på tålmodighet.' },
  { id: 15, name: 'Djevelen',            img: 'https://upload.wikimedia.org/wikipedia/commons/5/55/RWS_Tarot_15_Devil.jpg',              keywords: ['Binding', 'Skygge', 'Materiell fristelse'], meaning: 'Bindinger, avhengighet, materialisme, skyggesider. Reversert: Frihet fra bindinger, løsrivelse, konfrontasjon av skygger.' },
  { id: 16, name: 'Tårnet',              img: 'https://upload.wikimedia.org/wikipedia/commons/5/53/RWS_Tarot_16_Tower.jpg',              keywords: ['Kaos', 'Åpenbaring', 'Brudd'], meaning: 'Plutselig forandring, kaos, åpenbaring, omveltning. Reversert: Unngåelse av katastrofe, forsinket endring, motstand mot omveltning.' },
  { id: 17, name: 'Stjernen',            img: 'https://upload.wikimedia.org/wikipedia/commons/d/db/RWS_Tarot_17_Star.jpg',               keywords: ['Håp', 'Inspirasjon', 'Fornyelse'], meaning: 'Håp, tro, fornyelse, spiritualitet, inspirasjon. Reversert: Desperasjon, mangel på tro, motløshet.' },
  { id: 18, name: 'Månen',               img: 'https://upload.wikimedia.org/wikipedia/commons/7/7f/RWS_Tarot_18_Moon.jpg',               keywords: ['Illusjon', 'Underbevissthet', 'Frykt'], meaning: 'Illusjon, frykt, angst, underbevissthet, intuisjon. Reversert: Frigjøring av frykt, klarhet, avsløring av sannheter.' },
  { id: 19, name: 'Solen',               img: 'https://upload.wikimedia.org/wikipedia/commons/1/17/RWS_Tarot_19_Sun.jpg',                keywords: ['Glede', 'Suksess', 'Vitalitet'], meaning: 'Suksess, vitalitet, glede, optimisme, klarhet. Reversert: Midlertidig svikt, mangel på entusiasme, pessimisme.' },
  { id: 20, name: 'Dommen',              img: 'https://upload.wikimedia.org/wikipedia/commons/d/dd/RWS_Tarot_20_Judgement.jpg',          keywords: ['Oppvåkning', 'Tilgivelse', 'Transformasjon'], meaning: 'Gjenfødelse, dom, indre kall, tilgivelse. Reversert: Selv-dømmende, ignorering av kallet, tvil.' },
  { id: 21, name: 'Verden',              img: 'https://upload.wikimedia.org/wikipedia/commons/f/ff/RWS_Tarot_21_World.jpg',              keywords: ['Fullendelse', 'Integrering', 'Triumf'], meaning: 'Fullendelse, integrasjon, oppnåelse, reise. Reversert: Ufullstendighet, mangel på avslutning, stagnasjon.' },
];

export const MINOR_ARCANA = [
  // ── STAVER (Wands) – Ild / Handling / Kreativitet ──────────────────────────
  { id: 100, suit: 'staver', name: 'Es av Staver',       img: 'https://upload.wikimedia.org/wikipedia/commons/1/11/RWS_Tarot_Wands01.jpg', keywords: ['Nytt initiativ', 'Kreativ kraft', 'Gnist'], meaning: 'Ny idé, inspirasjon, mulighet, potensial. Reversert: Mangel på energi, forsinkelser, manglende retning.' },
  { id: 101, suit: 'staver', name: '2 av Staver',        img: 'https://upload.wikimedia.org/wikipedia/commons/0/0f/RWS_Tarot_Wands02.jpg', keywords: ['Planlegging', 'Fremtidsvision', 'Personlig makt'], meaning: 'Fremtidsplanlegging, beslutninger, oppdagelse. Reversert: Frykt for det ukjente, mangel på planlegging.' },
  { id: 102, suit: 'staver', name: '3 av Staver',        img: 'https://upload.wikimedia.org/wikipedia/commons/f/ff/RWS_Tarot_Wands03.jpg', keywords: ['Ekspansjon', 'Framsyn', 'Reise'], meaning: 'Ekspansjon, framsyn, lederskap, utenlandske muligheter. Reversert: Hindringer, forsinkelser, mangel på framsyn.' },
  { id: 103, suit: 'staver', name: '4 av Staver',        img: 'https://upload.wikimedia.org/wikipedia/commons/a/a4/RWS_Tarot_Wands04.jpg', keywords: ['Feiring', 'Harmoni', 'Hjemkomst'], meaning: 'Feiring, harmoni, hjemkomst, fellesskap. Reversert: Ustabil hjemmebase, mangel på harmoni.' },
  { id: 104, suit: 'staver', name: '5 av Staver',        img: 'https://upload.wikimedia.org/wikipedia/commons/9/9d/RWS_Tarot_Wands05.jpg', keywords: ['Konflikt', 'Konkurranse', 'Kaos'], meaning: 'Konflikt, konkurranse, uenighet, spenning. Reversert: Unngåelse av konflikt, enighet, løsning.' },
  { id: 105, suit: 'staver', name: '6 av Staver',        img: 'https://upload.wikimedia.org/wikipedia/commons/3/3b/RWS_Tarot_Wands06.jpg', keywords: ['Seier', 'Anerkjennelse', 'Suksess'], meaning: 'Seier, offentlig anerkjennelse, suksess, selvtillit. Reversert: Nederlag, mangel på anerkjennelse, arroganse.' },
  { id: 106, suit: 'staver', name: '7 av Staver',        img: 'https://upload.wikimedia.org/wikipedia/commons/e/e4/RWS_Tarot_Wands07.jpg', keywords: ['Forsvar', 'Utholdenhet', 'Utfordring'], meaning: 'Utfordring, konkurranse, beskyttelse, utholdenhet. Reversert: Overveldelse, gir opp, mangel på mot.' },
  { id: 107, suit: 'staver', name: '8 av Staver',        img: 'https://upload.wikimedia.org/wikipedia/commons/6/6b/RWS_Tarot_Wands08.jpg', keywords: ['Rask bevegelse', 'Kommunikasjon', 'Fart'], meaning: 'Rask handling, nyheter, reise, bevegelse. Reversert: Forsinkelser, frustrasjon, motstand mot endring.' },
  { id: 108, suit: 'staver', name: '9 av Staver',        img: 'https://upload.wikimedia.org/wikipedia/commons/4/4d/RWS_Tarot_Wands09.jpg', keywords: ['Motstandskraft', 'Grenser', 'Utmattelse'], meaning: 'Motstandskraft, mot, grenser, utholdenhet. Reversert: Utmattelse, paranoia, defensivitet.' },
  { id: 109, suit: 'staver', name: '10 av Staver',       img: 'https://upload.wikimedia.org/wikipedia/commons/0/0b/RWS_Tarot_Wands10.jpg', keywords: ['Byrde', 'Ansvar', 'Overbelastning'], meaning: 'Byrde, ansvar, overbelastning, stress. Reversert: Slippe byrder, dele ansvar, lettelse.' },
  { id: 110, suit: 'staver', name: 'Knekt av Staver',    img: 'https://upload.wikimedia.org/wikipedia/commons/6/6a/RWS_Tarot_Wands11.jpg', keywords: ['Entusiasme', 'Nysgjerrighet', 'Eventyr'], meaning: 'Ny idé, inspirasjon, mulighet, potensial. Reversert: Mangel på energi, forsinkelser, manglende retning.' },
  { id: 111, suit: 'staver', name: 'Ridder av Staver',   img: 'https://upload.wikimedia.org/wikipedia/commons/1/16/RWS_Tarot_Wands12.jpg', keywords: ['Lidenskap', 'Impulsivitet', 'Handling'], meaning: 'Lidenskap, eventyr, impulsivitet. Reversert: Hensynsløshet, utålmodighet, mangel på retning.' },
  { id: 112, suit: 'staver', name: 'Dronning av Staver', img: 'https://upload.wikimedia.org/wikipedia/commons/0/0d/RWS_Tarot_Wands13.jpg', keywords: ['Karisma', 'Selvtillit', 'Vitalitet'], meaning: 'Selvsikker, karismatisk, energisk. Reversert: Krevende, sjalu, utbrent.' },
  { id: 113, suit: 'staver', name: 'Konge av Staver',    img: 'https://upload.wikimedia.org/wikipedia/commons/c/ce/RWS_Tarot_Wands14.jpg', keywords: ['Visjonær leder', 'Inspirasjon', 'Modig autoritet'], meaning: 'Naturlig leder, visjonær, inspirerende. Reversert: Autoritær, utålmodig, impulsiv.' },

  // ── BEGER (Cups) – Vann / Følelser / Relasjoner ────────────────────────────
  { id: 200, suit: 'beger', name: 'Es av Beger',         img: 'https://upload.wikimedia.org/wikipedia/commons/3/35/RWS_Tarot_Cups01.jpg', keywords: ['Ny kjærlighet', 'Emosjonell åpning', 'Intuitiv gave'], meaning: 'Ny kjærlighet, kreativitet, følelser, intuisjon. Reversert: Undertrykte følelser, blokkert kreativitet.' },
  { id: 201, suit: 'beger', name: '2 av Beger',          img: 'https://upload.wikimedia.org/wikipedia/commons/f/f8/RWS_Tarot_Cups02.jpg', keywords: ['Partnerskap', 'Gjensidighet', 'Tiltrekning'], meaning: 'Forening, partnerskap, gjensidig tiltrekning. Reversert: Ubalanse i relasjoner, disharmoni.' },
  { id: 202, suit: 'beger', name: '3 av Beger',          img: 'https://upload.wikimedia.org/wikipedia/commons/7/7a/RWS_Tarot_Cups03.jpg', keywords: ['Feiring', 'Vennskap', 'Fellesskap'], meaning: 'Feiring, vennskap, fellesskap, kreativt samarbeid. Reversert: Overfladiskhet, sladder, isolasjon.' },
  { id: 203, suit: 'beger', name: '4 av Beger',          img: 'https://upload.wikimedia.org/wikipedia/commons/a/a4/RWS_Tarot_Cups04.jpg', keywords: ['Apati', 'Kontemplasjon', 'Savnet mulighet'], meaning: 'Apati, kontemplasjon, frakobling, savnede muligheter. Reversert: Tilbaketrekning, likegyldighet.' },
  { id: 204, suit: 'beger', name: '5 av Beger',          img: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/RWS_Tarot_Cups05.jpg', keywords: ['Sorg', 'Tap', 'Skuffelse'], meaning: 'Tap, sorg, skuffelse, anger. Reversert: Aksept, tilgivelse, å gå videre.' },
  { id: 205, suit: 'beger', name: '6 av Beger',          img: 'https://upload.wikimedia.org/wikipedia/commons/1/17/RWS_Tarot_Cups06.jpg', keywords: ['Nostalgi', 'Barndom', 'Uskyld'], meaning: 'Nostalgi, barndomsminner, uskyld, gjenforening. Reversert: Å være fast i fortiden, manglende vilje til å gå videre.' },
  { id: 206, suit: 'beger', name: '7 av Beger',          img: 'https://upload.wikimedia.org/wikipedia/commons/a/ae/RWS_Tarot_Cups07.jpg', keywords: ['Illusjoner', 'Fantasier', 'Valg'], meaning: 'Valg, illusjoner, fantasi, ønsketenkning. Reversert: Klarhet, besluttsomhet, å se realiteten.' },
  { id: 207, suit: 'beger', name: '8 av Beger',          img: 'https://upload.wikimedia.org/wikipedia/commons/6/60/RWS_Tarot_Cups08.jpg', keywords: ['Forlate', 'Søken', 'Desillusjonering'], meaning: 'Å forlate noe, å gå videre, skuffelse, søken etter mer. Reversert: Frykt for forandring, å bli værende i en dårlig situasjon.' },
  { id: 208, suit: 'beger', name: '9 av Beger',          img: 'https://upload.wikimedia.org/wikipedia/commons/2/24/RWS_Tarot_Cups09.jpg', keywords: ['Ønskeoppfyllelse', 'Tilfredshet', 'Lykke'], meaning: 'Ønskeoppfyllelse, tilfredshet, glede, velvære. Reversert: Utilfredshet, materialisme, skuffelse.' },
  { id: 209, suit: 'beger', name: '10 av Beger',         img: 'https://upload.wikimedia.org/wikipedia/commons/8/84/RWS_Tarot_Cups10.jpg', keywords: ['Harmoni', 'Familie', 'Emosjonell fullendelse'], meaning: 'Harmoni, ekteskap, lykke, familie. Reversert: Disharmoni i familien, ødelagte relasjoner.' },
  { id: 210, suit: 'beger', name: 'Knekt av Beger',      img: 'https://upload.wikimedia.org/wikipedia/commons/a/ad/RWS_Tarot_Cups11.jpg', keywords: ['Drømmende', 'Empatisk', 'Kreativt budskap'], meaning: 'Kreativ, romantisk, intuitiv. Reversert: Emosjonell umodenhet, eskapisme.' },
  { id: 211, suit: 'beger', name: 'Ridder av Beger',     img: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/RWS_Tarot_Cups12.jpg', keywords: ['Romantikk', 'Idealist', 'Sjarmerende'], meaning: 'Romantisk, sjarmerende, idealistisk. Reversert: Humørsyk, urealistisk, sjalu.' },
  { id: 212, suit: 'beger', name: 'Dronning av Beger',   img: 'https://upload.wikimedia.org/wikipedia/commons/6/62/RWS_Tarot_Cups13.jpg', keywords: ['Intuisjon', 'Medfølelse', 'Emosjonell visdom'], meaning: 'Medfølende, intuitiv, omsorgsfull. Reversert: Emosjonelt manipulerende, avhengig.' },
  { id: 213, suit: 'beger', name: 'Konge av Beger',      img: 'https://upload.wikimedia.org/wikipedia/commons/0/04/RWS_Tarot_Cups14.jpg', keywords: ['Emosjonell modenhet', 'Balansert følelser', 'Omsorgsfull leder'], meaning: 'Emosjonelt balansert, medfølende, diplomatisk. Reversert: Emosjonell manipulasjon, humørsvingninger.' },

  // ── SVERD (Swords) – Luft / Intellekt / Utfordringer ──────────────────────
  { id: 300, suit: 'sverd', name: 'Es av Sverd',         img: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/RWS_Tarot_Swords01.jpg', keywords: ['Klarhet', 'Sannhet', 'Mental kraft'], meaning: 'Gjennombrudd, ny idé, mental klarhet, sannhet. Reversert: Forvirring, uklarhet, feilkommunikasjon.' },
  { id: 301, suit: 'sverd', name: '2 av Sverd',          img: 'https://upload.wikimedia.org/wikipedia/commons/9/9e/RWS_Tarot_Swords02.jpg', keywords: ['Fastlåst', 'Unngåelse', 'Vanskelig valg'], meaning: 'Vanskelig valg, fastlåst situasjon, våpenhvile. Reversert: Ubesluttsomhet, forvirring, feilinformasjon.' },
  { id: 302, suit: 'sverd', name: '3 av Sverd',          img: 'https://upload.wikimedia.org/wikipedia/commons/0/02/RWS_Tarot_Swords03.jpg', keywords: ['Hjertesorg', 'Smerte', 'Svik'], meaning: 'Hjertesorg, sorg, smerte, avvisning. Reversert: Helbredelse, tilgivelse, å komme seg videre.' },
  { id: 303, suit: 'sverd', name: '4 av Sverd',          img: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/RWS_Tarot_Swords04.jpg', keywords: ['Hvile', 'Restitusjon', 'Kontemplasjon'], meaning: 'Hvile, restitusjon, kontemplasjon, pusterom. Reversert: Utbrenthet, stress, mangel på hvile.' },
  { id: 304, suit: 'sverd', name: '5 av Sverd',          img: 'https://upload.wikimedia.org/wikipedia/commons/2/21/RWS_Tarot_Swords05.jpg', keywords: ['Konflikt', 'Nederlag', 'Egosenter'], meaning: 'Konflikt, nederlag, uærlighet, vinne for enhver pris. Reversert: Forsoning, åpenhet for løsning.' },
  { id: 305, suit: 'sverd', name: '6 av Sverd',          img: 'https://upload.wikimedia.org/wikipedia/commons/2/29/RWS_Tarot_Swords06.jpg', keywords: ['Overgang', 'Flukt', 'Friere farvann'], meaning: 'Overgang, reise, å gå videre fra vanskeligheter. Reversert: Motstand mot endring, fastlåst.' },
  { id: 306, suit: 'sverd', name: '7 av Sverd',          img: 'https://upload.wikimedia.org/wikipedia/commons/3/34/RWS_Tarot_Swords07.jpg', keywords: ['List', 'Bedrag', 'Taktikk'], meaning: 'Bedrag, sniking, strategi, uærlighet. Reversert: Å bli avslørt, skyld, å innrømme feil.' },
  { id: 307, suit: 'sverd', name: '8 av Sverd',          img: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/RWS_Tarot_Swords08.jpg', keywords: ['Fanget', 'Begrensning', 'Selvpålagt fengsel'], meaning: 'Begrensning, isolasjon, selvpålagte restriksjoner, offerrolle. Reversert: Frihet, å se løsninger, å ta kontroll.' },
  { id: 308, suit: 'sverd', name: '9 av Sverd',          img: 'https://upload.wikimedia.org/wikipedia/commons/2/2f/RWS_Tarot_Swords09.jpg', keywords: ['Angst', 'Mareritt', 'Bekymring'], meaning: 'Angst, frykt, mareritt, bekymring, skyld. Reversert: Håp, å finne hjelp, å overvinne frykt.' },
  { id: 309, suit: 'sverd', name: '10 av Sverd',         img: 'https://upload.wikimedia.org/wikipedia/commons/d/d4/RWS_Tarot_Swords10.jpg', keywords: ['Endelig tap', 'Krise', 'Nødvendig slutt'], meaning: 'Smertefull slutt, nederlag, krise, svik. Reversert: Gjenoppretting, å se lys i tunnelen, uunngåelig slutt.' },
  { id: 310, suit: 'sverd', name: 'Knekt av Sverd',      img: 'https://upload.wikimedia.org/wikipedia/commons/4/4c/RWS_Tarot_Swords11.jpg', keywords: ['Analytisk', 'Direkte', 'Nysgjerrig intellekt'], meaning: 'Nysgjerrig, ærlig, direkte. Reversert: Frekk, defensiv, sladder.' },
  { id: 311, suit: 'sverd', name: 'Ridder av Sverd',     img: 'https://upload.wikimedia.org/wikipedia/commons/b/b0/RWS_Tarot_Swords12.jpg', keywords: ['Ambisiøs', 'Impulsiv handling', 'Intellektuell kraft'], meaning: 'Ambisiøs, handlekraftig, direkte. Reversert: Aggressiv, hensynsløs, fanatisk.' },
  { id: 312, suit: 'sverd', name: 'Dronning av Sverd',   img: 'https://upload.wikimedia.org/wikipedia/commons/d/d4/RWS_Tarot_Swords13.jpg', keywords: ['Skarpsindig', 'Uavhengig', 'Direkte kommunikasjon'], meaning: 'Uavhengig, intelligent, objektiv. Reversert: Kritisk, bitter, kald.' },
  { id: 313, suit: 'sverd', name: 'Konge av Sverd',      img: 'https://upload.wikimedia.org/wikipedia/commons/3/33/RWS_Tarot_Swords14.jpg', keywords: ['Intellektuell makt', 'Rettferdig dom', 'Analytisk leder'], meaning: 'Autoritær, intellektuell, rettferdig. Reversert: Manipulerende, tyrannisk, misbruker makt.' },

  // ── PENTAKLER (Pentacles) – Jord / Det materielle / Økonomi ───────────────
  { id: 400, suit: 'pentakler', name: 'Es av Pentakler',       img: 'https://upload.wikimedia.org/wikipedia/commons/f/fd/RWS_Tarot_Pentacles01.jpg', keywords: ['Materiell start', 'Ny mulighet', 'Overflod'], meaning: 'Ny mulighet, manifestasjon, velstand. Reversert: Tapt mulighet, dårlig investering.' },
  { id: 401, suit: 'pentakler', name: '2 av Pentakler',        img: 'https://upload.wikimedia.org/wikipedia/commons/9/9f/RWS_Tarot_Pentacles02.jpg', keywords: ['Balanse', 'Jonglering', 'Tilpasningsevne'], meaning: 'Balanse, tilpasningsevne, prioritering, jonglering. Reversert: Ubalanse, dårlig organisering.' },
  { id: 402, suit: 'pentakler', name: '3 av Pentakler',        img: 'https://upload.wikimedia.org/wikipedia/commons/4/42/RWS_Tarot_Pentacles03.jpg', keywords: ['Samarbeid', 'Håndverk', 'Læring'], meaning: 'Samarbeid, mestring, læring, anerkjennelse. Reversert: Dårlig samarbeid, middelmådighet.' },
  { id: 403, suit: 'pentakler', name: '4 av Pentakler',        img: 'https://upload.wikimedia.org/wikipedia/commons/3/35/RWS_Tarot_Pentacles04.jpg', keywords: ['Gjerrighet', 'Sikkerhet', 'Kontroll'], meaning: 'Kontroll, sikkerhet, besittelse, gjerrighet. Reversert: Slippe kontroll, generøsitet, åpenhet.' },
  { id: 404, suit: 'pentakler', name: '5 av Pentakler',        img: 'https://upload.wikimedia.org/wikipedia/commons/9/96/RWS_Tarot_Pentacles05.jpg', keywords: ['Fattigdom', 'Isolasjon', 'Hardship'], meaning: 'Fattigdom, motgang, isolasjon, usikkerhet. Reversert: Gjenoppretting fra tap, hjelp.' },
  { id: 405, suit: 'pentakler', name: '6 av Pentakler',        img: 'https://upload.wikimedia.org/wikipedia/commons/d/d6/RWS_Tarot_Pentacles06.jpg', keywords: ['Generøsitet', 'Veldedighet', 'Balanse i gi og ta'], meaning: 'Generøsitet, veldedighet, å gi og motta. Reversert: Gjeld, egoisme, ubalansert utveksling.' },
  { id: 406, suit: 'pentakler', name: '7 av Pentakler',        img: 'https://upload.wikimedia.org/wikipedia/commons/6/6a/RWS_Tarot_Pentacles07.jpg', keywords: ['Tålmodighet', 'Investering', 'Langsiktig vekst'], meaning: 'Tålmodighet, langsiktig visjon, investering, belønning. Reversert: Utålmodighet, kortsiktig gevinst.' },
  { id: 407, suit: 'pentakler', name: '8 av Pentakler',        img: 'https://upload.wikimedia.org/wikipedia/commons/4/49/RWS_Tarot_Pentacles08.jpg', keywords: ['Flid', 'Mestring', 'Dedikert arbeid'], meaning: 'Håndverk, ferdigheter, repetisjon, flid. Reversert: Perfeksjonisme, middelmådig arbeid.' },
  { id: 408, suit: 'pentakler', name: '9 av Pentakler',        img: 'https://upload.wikimedia.org/wikipedia/commons/f/f0/RWS_Tarot_Pentacles09.jpg', keywords: ['Selvforsynt', 'Luksus', 'Uavhengighet'], meaning: 'Overflod, uavhengighet, luksus, selvtillit. Reversert: Materiell avhengighet, overfladiskhet.' },
  { id: 409, suit: 'pentakler', name: '10 av Pentakler',       img: 'https://upload.wikimedia.org/wikipedia/commons/4/46/RWS_Tarot_Pentacles10.jpg', keywords: ['Arv', 'Familieverdi', 'Materiell fullendelse'], meaning: 'Rikdom, arv, familie, etablering. Reversert: Familiekonflikt, tap av arv, finansiell ustabilitet.' },
  { id: 410, suit: 'pentakler', name: 'Knekt av Pentakler',    img: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/RWS_Tarot_Pentacles11.jpg', keywords: ['Ambisiøs student', 'Pålitelig', 'Praktisk læring'], meaning: 'Manifestasjon, muligheter, læring. Reversert: Mangel på fremgang, prokrastinering.' },
  { id: 411, suit: 'pentakler', name: 'Ridder av Pentakler',   img: 'https://upload.wikimedia.org/wikipedia/commons/8/8d/RWS_Tarot_Pentacles12.jpg', keywords: ['Tålmodig', 'Metodisk', 'Hardtarbeidende'], meaning: 'Effektiv, pålitelig, hardtarbeidende. Reversert: Kjedelig, lat, sta.' },
  { id: 412, suit: 'pentakler', name: 'Dronning av Pentakler', img: 'https://upload.wikimedia.org/wikipedia/commons/d/d5/RWS_Tarot_Pentacles13.jpg', keywords: ['Nærende', 'Praktisk klokskap', 'Jordnær omsorg'], meaning: 'Praktisk, omsorgsfull, jordnær. Reversert: Materialistisk, overbeskyttende, rotete.' },
  { id: 413, suit: 'pentakler', name: 'Konge av Pentakler',    img: 'https://upload.wikimedia.org/wikipedia/commons/1/1c/RWS_Tarot_Pentacles14.jpg', keywords: ['Velstand', 'Forretningssans', 'Trygg autoritet'], meaning: 'Velstående, sjenerøs, trygg. Reversert: Grådig, materialistisk, hensynsløs.' },
];

export const FULL_TAROT_DECK = [...MAJOR_ARCANA, ...MINOR_ARCANA];
