
import { Author, MethodologyType, Resource, Course } from './types';

export const UI_TRANSLATIONS: Record<string, any> = {
  no: {
    navDashboard: 'Dashboard',
    navProfile: 'Sjelssenter',
    navAstrology: 'Astrologi',
    navNumerology: 'Numerologi',
    navTarot: 'Tarot',
    navHoroscope: 'Horoskop',
    navChineseAstrology: 'Kinesisk',
    navTools: 'Verktøy',
    navSettings: 'Innstillinger',
    navLogout: 'Logg ut',
    welcomeBack: 'Velkommen tilbake til arkivene',
    soulOverview: 'Sjelens Oversikt',
    dailyEnergy: 'Dagens Energi',
    emotionalWave: 'Følelsesmessig Bølge',
    cosmicWeather: 'Kosmisk Vær',
    startJourney: 'Start Min Kronike',
    natalTitle: 'Ditt Opprinnelige Kart',
    relocationTitle: 'Flytting',
    transitTitle: 'Transitter',
    vedicTitle: 'Vedic',
    esotericTitle: 'Esoterisk',
    classicalTitle: 'Klassisk',
    modernTitle: 'Moderne',
    writeBook: 'Skriv Min Livsbok',
    archiveReport: 'Arkiver Rapport',
    printReport: 'Skriv ut Rapport',
    languageName: 'Norsk',
    periodDay: 'I dag',
    periodWeek: 'Denne uken',
    periodMonth: 'Denne måneden',
    periodYear: 'Hele året',
    horoscopeTitle: 'Ditt Personlige Horoskop',
    horoscopeSubtitle: 'Basert på sjelens transitter',
    chineseTitle: 'Kinesisk Horoskop',
    chineseSubtitle: 'De fire søyler og elementenes balanse',
    traditionLabel: 'Tradisjon',
    analysisLabel: 'Analyse',
    saveProfileBtn: 'Oppdater Sjelsprofil',
    saveSuccess: 'Data er trygt arkivert i din sjelsprofil',
    nameLabel: 'Navn for Vibrasjon',
    birthDateLabel: 'Fødselsdato',
    birthTimeLabel: 'Klokkeslett',
    birthLocationLabel: 'Fødested',
    houseSystemLabel: 'Foretrukket Hussystem',
    apiKeysTitle: 'Personlige Arkivnøkler',
    apiKeysDesc: 'Disse nøklene brukes for å åpne de dype AI-analysene.',
    appearanceTitle: 'App-utseende',
    lightMode: 'Lys',
    darkMode: 'Mørk',
    archiveTitle: 'Mine Lagrede Innsikter',
    noArchiveDesc: 'Ditt arkiv venter på sin første historie...',
    readInsight: 'Les Innsikt',
    backToArchive: 'Tilbake til Arkivet',
    technicalInventory: 'Teknisk Inventar',
    transformationCycles: 'Transformasjon & Sykluser',
    powerMantraLabel: 'Ditt Makt-Mantra',
    statusLabel: 'Status',
    loadingCoords: 'Dechiffrerer dine kosmiske koordinater...',
    masterMemberLabel: 'Master-Medlem',
    creditsLabel: 'Kreditter',
    noProfileTitle: 'Fødselstid og dato mangler',
    noProfileDesc: 'For å se ditt stjernekart og personlige horoskop trenger AstroMason nøyaktig informasjon om din inkarnasjon.',
    updateProfileNow: 'Oppdater Sjelsprofil Nå',
    astrologyHub: 'Astrologi Hub',
    cosmicCompass: 'Ditt kosmiske kompass',
    tabChart: 'Kart',
    tabHoroscope: 'Horoskop',
    tabLifeBook: 'Livsbok',
    tabSolarReturn: 'Solretur',
    tabProgression: 'Progresjon',
    tabCalendar: 'Kalender',
    planetaryPositions: 'Planetariske Posisjoner',
    annualProfections: 'Årsprofesjoner',
    ageLabel: 'Alder',
    traditionalLabel: 'Tradisjonell',
    houseLabel: 'Hus',
    yearLord: 'Årets Herre',
    profectedSign: 'Profektert tegn',
    profectionYearDesc: 'Hvert leveår aktiverer et nytt hus. Dette er den kosmiske energien som preger ditt neste leveår.',
    soulChronicle: 'Din Sjels Kronike',
    soulChronicleDesc: 'En dyptgående AI-analyse på 4000+ ord som dechiffrerer din sjel, dine karmiske bånd og ditt fulle potensial i denne inkarnasjonen.',
    writeLifeBookNow: 'Skriv Min Livsbok Nå',
    priceCredits: 'Pris: 5 Kreditter • 4000+ Ord',
    archivesDecoding: 'Arkivene dechiffreres...',
    connectionError: 'Kunne ikke koble til de dype arkivene akkurat nå.',
    generatingReport: 'AstroMason dechiffrerer din sjel...',
    sunTodayLabel: 'Solen i dag',
    sunVitality: 'Din livskraft og ytre identitet',
    moonLabel: 'Månen',
    emotionalFlow: 'Følelsesmessig strøm akkurat nå',
    dailyTarotCard: 'Dagens Tarot-Kort',
    numerologyCycles: 'Numerologiske Sykler',
    personalYearLabel: 'Personlig År',
    personalMonthLabel: 'Personlig Måned',
    numerologyNowDesc: 'Numerologisk energi akkurat nå — klikk for dypanalyse',
    activeTransitsNow: 'Aktive Transitter Akkurat Nå',
    seeChartArrow: 'Se kart →',
    astrologicalAnalysis: 'Astrologisk Analyse',
    astrologicalAnalysisDesc: 'Dykk dypt ned i ditt fødselshoroskop, sjekk din relasjons-synergi eller se dine kommende transitter.',
    openStarMap: 'Åpne Stjernekartet',
    personalHoroscopeShort: 'Ditt Personlige Horoskop',
    personalHoroscopeDesc: 'Dag, uke, måned eller år — basert på ditt natale kart.',
    coupleHoroscope: 'Par-Horoskop & Verktøy',
    toolsDesc: 'Synastri, relokasjon og ukentlig transit-prognose.',
    chineseShort: 'Kinesisk',
    fiveElements: 'Fem elementer',
    numerologyShort: 'Tallkode',
    soulVibrationShort: 'Sjelens vibrasjon',
    tarotSynthesis: 'Tarot-Syntese',
    tarotSynthesisDesc: 'Spør orakelet og dechiffrer sjelens speil.',
    sunNow: 'Solen akkurat nå',
    cosmicBalance: 'Kosmisk Balanse',
    planetsForward: 'Planetene beveger seg fremover',
    allInnerPlanetsForward: 'Alle indre planeter beveger seg fremover',
    retrogradeRevision: 'beveger seg bakover — tid for revisjon',
    forwardMotion: 'Fremovergang',
    unknownPhase: 'Ukjent fase',
    moonPhases: ['Nymåne','Voksende halvmåne','Første kvarter','Voksende gibbous','Fullmåne','Avtagende gibbous','Siste kvarter','Avtagende halvmåne'],
    zodiacSigns: ['Væren','Tyren','Tvillingene','Krepsen','Løven','Jomfruen','Vekten','Skorpionen','Skytten','Steinbukken','Vannmannen','Fiskene'],
    houseThemes: {1:'Identitet & ny start',2:'Ressurser & verdier',3:'Kommunikasjon & søsken',4:'Hjem & røtter',5:'Kreativitet & kjærlighet',6:'Helse & daglig arbeid',7:'Partnerskap & relasjoner',8:'Transformasjon & delt ressurs',9:'Visdom & reise',10:'Karriere & offentlig liv',11:'Nettverk & drømmer',12:'Det skjulte & åndelig vekst'},
    chineseConnectionError: 'Forbindelsen til de østlige arkivene er midlertidig brutt.',
    chineseCreditsNeeded: 'Denne analysen krever {n} kreditter. Du blir nå ledet til arkivet for påfyll.',
    aiGreeting: 'Hei! Jeg er AstroMason AI — din personlige kosmiske veileder. Spør meg om ditt kart, transitter, kjærlighet, karriere eller åndelig vekst. Jeg er her for deg.',
    aiSubtitle: 'Kosmisk Veileder',
    aiPlaceholder: 'Spør AstroMason...',
    aiNeedCredits: 'Trenger kreditter eller Master-abonnement',
    aiError: 'De kosmiske arkivene er midlertidig utilgjengelige. Prøv igjen om et øyeblikk.',
    numerology: {
      soulMapTitle: 'Sjelens Fullstendige Tallkart',
      cyclesTitle: 'Tidens Hjul & Utfordringer',
      karmaAlert: 'Karmisk Gjeld Detektert',
      coreFour: 'De Fire Kjernevibrasjoner'
    },
    tarot: {
      spreadOneCard: 'Dagens Kort (1 Kort)',
      spreadThreeTime: 'Tiden (3 Kort)',
      spreadRelationship: 'Relasjonen (3 Kort)',
      spreadCelticCross: 'Keltisk Kors (10 Kort)',
      posSoulMessage: 'Sjelens Budskap',
      posPast: 'Fortid', posPresent: 'Nåtid', posFuture: 'Fremtid',
      posYou: 'Deg', posOther: 'Den Andre', posDynamic: 'Dynamikken',
      posCore: 'Kjernen', posChallenge: 'Utfordring', posGoal: 'Mål',
      posRoots: 'Røtter', posSelf: 'Selvet', posEnvironment: 'Omgivelser',
      posFear: 'Frykt', posOutcome: 'Utfall',
      styleEsoteric: 'Esoterisk', styleEsotericDesc: 'Sjelens skjulte språk',
      stylePsychological: 'Psykologisk', stylePsychologicalDesc: 'Jungiansk dybde',
      styleClassical: 'Klassisk', styleClassicalDesc: 'Tradisjonell innsikt',
      noCreditsMsg: 'Du har 0 kosmiske kreditter. Vil du fylle på i arkivet?'
    },
    landing: {
      heroTitle: 'Din Sjels',
      heroSubtitle: 'Kronike',
      heroDesc: 'Gå forbi overfladiske horoskop. Astro Mason dechiffrerer din sjel gjennom esoterisk astrologi, dyp tarot og hellig numerologi.',
      startBtn: 'Start Reisen',
      createArchive: 'Opprett ditt Arkiv',
      login: 'Logg inn',
      investmentTitle: 'Sjelelig Investering',
      investmentDesc: 'Velg din vei til selvinnsikt',
      singleTitle: 'Enkeltreise',
      singlePrice: '€14',
      singleUnit: '/ rapport',
      singleDesc: 'Perfekt for et dypdykk i din nåværende situasjon eller et spesifikt spørsmål.',
      singleFeatures: ['Komplett "Livsbok" (4000+ ord)', 'Dyp personlig analyse', 'Evig tilgang til rapport'],
      masterTitle: 'Mester-medlemskap',
      masterPrice: '€49',
      masterUnit: '/ år',
      masterDesc: 'Full og ubegrenset tilgang til alle arkiver, tarot-legg og numerologiske koder.',
      masterFeatures: ['Ubegrenset Astro-rapporter', 'Full tilgang til Tarot-modul', 'Alle numerologiske koder', 'Personlig innsiktshub'],
      bestValue: 'Beste Verdi',
      selectPlan: 'Velg denne',
      selectMaster: 'Velg Mester-veien',
      authTitleLogin: 'Velkommen Tilbake',
      authTitleReg: 'Opprett Sjelsprofil',
      authDesc: 'Gå inn i de dype arkivene',
      emailLabel: 'E-postadresse',
      passLabel: 'Passord',
      loginBtn: 'Logg inn',
      regBtn: 'Registrer Bruker',
      noAccount: 'Har du ikke konto?',
      hasAccount: 'Har du allerede konto?',
      clickHere: 'Klikk her',
      forgotTitle: 'Gjenopprett Tilgang',
      forgotSentMsg: 'Gjenopprettingslenke er sendt til',
      backToLogin: 'Tilbake til innlogging',
      demoModeNote: 'Demo-modus · Koble til Supabase for ekte auth',
      demoNoEmail: 'Demo-modus: ingen e-post sendt. Koble til Supabase for ekte e-post.',
      namePlaceholder: 'Ditt Navn',
      sendRecovery: 'Send Gjenoppretting',
      forgotPassword: 'Glemt passord?',
      errorResetFailed: 'Kunne ikke sende gjenopprettingslenke. Sjekk e-postadressen.',
      errorAlreadyReg: 'E-posten er allerede registrert. Logg inn i stedet.',
      errorPasswordShort: 'Passordet må være minst 6 tegn.',
      errorRegFailed: 'Registrering mislyktes. Prøv igjen.',
      errorInvalidCred: 'Feil e-post eller passord.',
      errorEmailNotConfirmed: 'Bekreft e-postadressen din først. Sjekk innboksen.',
      errorLoginFailed: 'Innlogging mislyktes. Prøv igjen.',
      errorGeneral: 'Noe gikk galt. Prøv igjen.'
    }
  },
  en: {
    navDashboard: 'Dashboard',
    navProfile: 'Soul Center',
    navAstrology: 'Astrology',
    navNumerology: 'Numerology',
    navTarot: 'Tarot',
    navHoroscope: 'Horoscope',
    navChineseAstrology: 'Chinese',
    navTools: 'Tools',
    navSettings: 'Settings',
    navLogout: 'Logout',
    welcomeBack: 'Welcome back to the archives',
    soulOverview: 'Soul Overview',
    dailyEnergy: 'Daily Energy',
    emotionalWave: 'Emotional Wave',
    cosmicWeather: 'Cosmic Weather',
    startJourney: 'Start My Chronicle',
    natalTitle: 'Your Natal Chart',
    relocationTitle: 'Relocation',
    transitTitle: 'Transits',
    vedicTitle: 'Vedic',
    esotericTitle: 'Esoteric',
    classicalTitle: 'Classical',
    modernTitle: 'Modern',
    writeBook: 'Write My Life Book',
    archiveReport: 'Archive Report',
    printReport: 'Print Report',
    languageName: 'English',
    periodDay: 'Today',
    periodWeek: 'This Week',
    periodMonth: 'This Month',
    periodYear: 'This Year',
    horoscopeTitle: 'Your Personal Horoscope',
    horoscopeSubtitle: 'Based on soul transits',
    chineseTitle: 'Chinese Horoscope',
    chineseSubtitle: 'The four pillars and balance of elements',
    traditionLabel: 'Tradition',
    analysisLabel: 'Analysis',
    saveProfileBtn: 'Update Soul Profile',
    saveSuccess: 'Data successfully archived in your soul profile',
    nameLabel: 'Name for Vibration',
    birthDateLabel: 'Birth Date',
    birthTimeLabel: 'Birth Time',
    birthLocationLabel: 'Birth Location',
    houseSystemLabel: 'Preferred House System',
    apiKeysTitle: 'Personal Archive Keys',
    apiKeysDesc: 'These keys are used to open deep AI analyses.',
    appearanceTitle: 'App Appearance',
    lightMode: 'Light',
    darkMode: 'Dark',
    archiveTitle: 'My Saved Insights',
    noArchiveDesc: 'Your archive awaits its first story...',
    readInsight: 'Read Insight',
    backToArchive: 'Back to Archive',
    technicalInventory: 'Technical Inventory',
    transformationCycles: 'Transformation & Cycles',
    powerMantraLabel: 'Your Power Mantra',
    statusLabel: 'Status',
    loadingCoords: 'Deciphering your cosmic coordinates...',
    masterMemberLabel: 'Master Member',
    creditsLabel: 'Credits',
    noProfileTitle: 'Birth date and time missing',
    noProfileDesc: 'To see your birth chart and personal horoscope, AstroMason needs accurate information about your incarnation.',
    updateProfileNow: 'Update Soul Profile Now',
    astrologyHub: 'Astrology Hub',
    cosmicCompass: 'Your cosmic compass',
    tabChart: 'Chart',
    tabHoroscope: 'Horoscope',
    tabLifeBook: 'Life Book',
    tabSolarReturn: 'Solar Return',
    tabProgression: 'Progressions',
    tabCalendar: 'Calendar',
    planetaryPositions: 'Planetary Positions',
    annualProfections: 'Annual Profections',
    ageLabel: 'Age',
    traditionalLabel: 'Traditional',
    houseLabel: 'House',
    yearLord: 'Year Lord',
    profectedSign: 'Profected Sign',
    profectionYearDesc: 'Each year of life activates a new house. This is the cosmic energy shaping your next year of life.',
    soulChronicle: 'Your Soul\'s Chronicle',
    soulChronicleDesc: 'A deep AI analysis of 4000+ words that deciphers your soul, karmic bonds, and full potential in this incarnation.',
    writeLifeBookNow: 'Write My Life Book Now',
    priceCredits: 'Price: 5 Credits • 4000+ Words',
    archivesDecoding: 'Decoding the archives...',
    connectionError: 'Could not connect to the deep archives right now.',
    generatingReport: 'AstroMason is deciphering your soul...',
    sunTodayLabel: 'Sun Today',
    sunVitality: 'Your life force and outer identity',
    moonLabel: 'Moon',
    emotionalFlow: 'Emotional current right now',
    dailyTarotCard: 'Daily Tarot Card',
    numerologyCycles: 'Numerology Cycles',
    personalYearLabel: 'Personal Year',
    personalMonthLabel: 'Personal Month',
    numerologyNowDesc: 'Numerological energy right now — click for deep analysis',
    activeTransitsNow: 'Active Transits Right Now',
    seeChartArrow: 'See chart →',
    astrologicalAnalysis: 'Astrological Analysis',
    astrologicalAnalysisDesc: 'Dive deep into your birth chart, check your relationship synergy, or view your upcoming transits.',
    openStarMap: 'Open Star Chart',
    personalHoroscopeShort: 'Your Personal Horoscope',
    personalHoroscopeDesc: 'Day, week, month or year — based on your natal chart.',
    coupleHoroscope: 'Couple Horoscope & Tools',
    toolsDesc: 'Synastry, relocation and weekly transit forecast.',
    chineseShort: 'Chinese',
    fiveElements: 'Five elements',
    numerologyShort: 'Number Code',
    soulVibrationShort: 'Soul vibration',
    tarotSynthesis: 'Tarot Synthesis',
    tarotSynthesisDesc: 'Ask the oracle and decipher the soul\'s mirror.',
    sunNow: 'Sun right now',
    cosmicBalance: 'Cosmic Balance',
    planetsForward: 'Planets moving forward',
    allInnerPlanetsForward: 'All inner planets moving forward',
    retrogradeRevision: 'moving retrograde — time for revision',
    forwardMotion: 'Direct Motion',
    unknownPhase: 'Unknown phase',
    moonPhases: ['New Moon','Waxing Crescent','First Quarter','Waxing Gibbous','Full Moon','Waning Gibbous','Last Quarter','Waning Crescent'],
    zodiacSigns: ['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'],
    houseThemes: {1:'Identity & New Beginning',2:'Resources & Values',3:'Communication & Siblings',4:'Home & Roots',5:'Creativity & Love',6:'Health & Daily Work',7:'Partnership & Relations',8:'Transformation & Shared Resources',9:'Wisdom & Travel',10:'Career & Public Life',11:'Networks & Dreams',12:'The Hidden & Spiritual Growth'},
    chineseConnectionError: 'Connection to the eastern archives is temporarily down.',
    chineseCreditsNeeded: 'This analysis requires {n} credits. You will now be directed to the archive for a top-up.',
    aiGreeting: 'Hello! I am AstroMason AI — your personal cosmic guide. Ask me about your chart, transits, love, career or spiritual growth. I am here for you.',
    aiSubtitle: 'Cosmic Guide',
    aiPlaceholder: 'Ask AstroMason...',
    aiNeedCredits: 'Requires credits or Master subscription',
    aiError: 'The cosmic archives are temporarily unavailable. Please try again in a moment.',
    numerology: {
      soulMapTitle: 'Complete Soul Map',
      cyclesTitle: 'Wheel of Time & Challenges',
      karmaAlert: 'Karmic Debt Detected',
      coreFour: 'The Core Four Vibrations'
    },
    tarot: {
      spreadOneCard: 'Daily Card (1 Card)',
      spreadThreeTime: 'Time (3 Cards)',
      spreadRelationship: 'The Relationship (3 Cards)',
      spreadCelticCross: 'Celtic Cross (10 Cards)',
      posSoulMessage: 'Soul\'s Message',
      posPast: 'Past', posPresent: 'Present', posFuture: 'Future',
      posYou: 'You', posOther: 'The Other', posDynamic: 'The Dynamic',
      posCore: 'The Core', posChallenge: 'Challenge', posGoal: 'Goal',
      posRoots: 'Roots', posSelf: 'The Self', posEnvironment: 'Environment',
      posFear: 'Fear', posOutcome: 'Outcome',
      styleEsoteric: 'Esoteric', styleEsotericDesc: 'Hidden language of the soul',
      stylePsychological: 'Psychological', stylePsychologicalDesc: 'Jungian depth',
      styleClassical: 'Classical', styleClassicalDesc: 'Traditional insight',
      noCreditsMsg: 'You have 0 cosmic credits. Would you like to top up in the archive?'
    },
    landing: {
      heroTitle: 'Chronicle of',
      heroSubtitle: 'Your Soul',
      heroDesc: 'Go beyond shallow horoscopes. Astro Mason deciphers your soul through esoteric astrology, deep tarot, and sacred numerology.',
      startBtn: 'Start Journey',
      createArchive: 'Create Your Archive',
      login: 'Login',
      investmentTitle: 'Soul Investment',
      investmentDesc: 'Choose your path to self-insight',
      singleTitle: 'Single Journey',
      singlePrice: '€14',
      singleUnit: '/ report',
      singleDesc: 'Perfect for a deep dive into your current situation or a specific question.',
      singleFeatures: ['Complete "Life Book" (4000+ words)', 'Deep personal analysis', 'Lifetime access to report'],
      masterTitle: 'Master Membership',
      masterPrice: '€49',
      masterUnit: '/ year',
      masterDesc: 'Full and unlimited access to all archives, tarot spreads, and numerological codes.',
      masterFeatures: ['Unlimited Astro Reports', 'Full Tarot Module Access', 'All Numerological Codes', 'Personal Insight Hub'],
      bestValue: 'Best Value',
      selectPlan: 'Select Plan',
      selectMaster: 'Choose Master Path',
      authTitleLogin: 'Welcome Back',
      authTitleReg: 'Create Soul Profile',
      authDesc: 'Enter the deep archives',
      emailLabel: 'Email Address',
      passLabel: 'Password',
      loginBtn: 'Login',
      regBtn: 'Register',
      noAccount: 'No account?',
      hasAccount: 'Already have an account?',
      clickHere: 'Click here',
      forgotTitle: 'Recover Access',
      forgotSentMsg: 'Recovery link sent to',
      backToLogin: 'Back to login',
      demoModeNote: 'Demo mode · Connect Supabase for real auth',
      demoNoEmail: 'Demo mode: no email sent. Connect Supabase for real emails.',
      namePlaceholder: 'Your Name',
      sendRecovery: 'Send Recovery',
      forgotPassword: 'Forgot password?',
      errorResetFailed: 'Could not send recovery link. Check the email address.',
      errorAlreadyReg: 'Email already registered. Login instead.',
      errorPasswordShort: 'Password must be at least 6 characters.',
      errorRegFailed: 'Registration failed. Please try again.',
      errorInvalidCred: 'Wrong email or password.',
      errorEmailNotConfirmed: 'Please confirm your email first. Check your inbox.',
      errorLoginFailed: 'Login failed. Please try again.',
      errorGeneral: 'Something went wrong. Please try again.'
    }
  },
  fr: {
    navDashboard: 'Tableau de bord',
    navProfile: 'Centre de l\'Âme',
    navAstrology: 'Astrologie',
    navNumerology: 'Numérologie',
    navTarot: 'Tarot',
    navHoroscope: 'Horoscope',
    navChineseAstrology: 'Chinois',
    navTools: 'Outils',
    navSettings: 'Paramètres',
    navLogout: 'Déconnexion',
    welcomeBack: 'Bienvenue dans les archives',
    soulOverview: 'Aperçu de l\'Âme',
    dailyEnergy: 'Énergie du Jour',
    emotionalWave: 'Vague Émotionnelle',
    cosmicWeather: 'Météo Cosmique',
    startJourney: 'Démarrer ma Chronique',
    natalTitle: 'Votre Carte du Ciel',
    relocationTitle: 'Relocalisation',
    transitTitle: 'Transits',
    vedicTitle: 'Védique',
    esotericTitle: 'Ésotérique',
    classicalTitle: 'Classique',
    modernTitle: 'Moderne',
    writeBook: 'Écrire mon Livre de Vie',
    archiveReport: 'Archiver le Rapport',
    printReport: 'Imprimer le Rapport',
    languageName: 'Français',
    periodDay: 'Aujourd\'hui',
    periodWeek: 'Cette Semaine',
    periodMonth: 'Ce Mois',
    periodYear: 'Cette Année',
    horoscopeTitle: 'Votre Horoscope Personnel',
    horoscopeSubtitle: 'Basé sur les transits de l\'âme',
    chineseTitle: 'Horoscope Chinois',
    chineseSubtitle: 'Les quatre piliers et l\'équilibre des éléments',
    traditionLabel: 'Tradition',
    analysisLabel: 'Analyse',
    saveProfileBtn: 'Mettre à jour le Profil',
    saveSuccess: 'Données archivées avec succès',
    nameLabel: 'Nom de Vibration',
    birthDateLabel: 'Date de Naissance',
    birthTimeLabel: 'Heure de Naissance',
    birthLocationLabel: 'Lieu de Naissance',
    houseSystemLabel: 'Système de Maisons',
    apiKeysTitle: 'Clés d\'Archive',
    apiKeysDesc: 'Ces clés ouvrent les analyses IA profondes.',
    appearanceTitle: 'Apparence',
    lightMode: 'Clair',
    darkMode: 'Sombre',
    archiveTitle: 'Mes Aperçus Enregistrés',
    noArchiveDesc: 'Votre archive attend sa première histoire...',
    readInsight: 'Lire l\'Aperçu',
    backToArchive: 'Retour à l\'Archive',
    technicalInventory: 'Inventaire Technique',
    transformationCycles: 'Transformation & Cycles',
    powerMantraLabel: 'Votre Mantra de Pouvoir',
    statusLabel: 'Statut',
    loadingCoords: 'Déchiffrement de vos coordonnées cosmiques...',
    masterMemberLabel: 'Membre Maître',
    creditsLabel: 'Crédits',
    noProfileTitle: 'Date et heure de naissance manquantes',
    noProfileDesc: 'Pour voir votre thème natal et votre horoscope, AstroMason a besoin des informations précises de votre incarnation.',
    updateProfileNow: 'Mettre à jour le Profil',
    astrologyHub: 'Hub Astrologique',
    cosmicCompass: 'Votre boussole cosmique',
    tabChart: 'Carte',
    tabHoroscope: 'Horoscope',
    tabLifeBook: 'Livre de Vie',
    tabSolarReturn: 'Révolution Solaire',
    tabProgression: 'Progressions',
    tabCalendar: 'Calendrier',
    planetaryPositions: 'Positions Planétaires',
    annualProfections: 'Profections Annuelles',
    ageLabel: 'Âge',
    traditionalLabel: 'Traditionnel',
    houseLabel: 'Maison',
    yearLord: 'Seigneur de l\'Année',
    profectedSign: 'Signe Profecté',
    profectionYearDesc: 'Chaque année de vie active une nouvelle maison. C\'est l\'énergie cosmique de votre prochaine année.',
    soulChronicle: 'La Chronique de Votre Âme',
    soulChronicleDesc: 'Une analyse IA approfondie de 4000+ mots qui déchiffre votre âme, vos liens karmiques et votre plein potentiel.',
    writeLifeBookNow: 'Écrire mon Livre de Vie',
    priceCredits: 'Prix: 5 Crédits • 4000+ Mots',
    archivesDecoding: 'Décodage des archives...',
    connectionError: 'Impossible de se connecter aux archives profondes.',
    generatingReport: 'AstroMason déchiffre votre âme...',
    sunTodayLabel: 'Soleil aujourd\'hui',
    sunVitality: 'Votre force vitale et identité extérieure',
    moonLabel: 'Lune',
    emotionalFlow: 'Courant émotionnel en ce moment',
    dailyTarotCard: 'Carte Tarot du Jour',
    numerologyCycles: 'Cycles Numérologique',
    personalYearLabel: 'Année Personnelle',
    personalMonthLabel: 'Mois Personnel',
    numerologyNowDesc: 'Énergie numérologique maintenant — cliquer pour analyse',
    activeTransitsNow: 'Transits Actifs en ce Moment',
    seeChartArrow: 'Voir carte →',
    astrologicalAnalysis: 'Analyse Astrologique',
    astrologicalAnalysisDesc: 'Plongez dans votre thème natal, vérifiez votre synergie ou voyez vos transits à venir.',
    openStarMap: 'Ouvrir la Carte des Étoiles',
    personalHoroscopeShort: 'Votre Horoscope Personnel',
    personalHoroscopeDesc: 'Jour, semaine, mois ou année — basé sur votre thème natal.',
    coupleHoroscope: 'Horoscope de Couple & Outils',
    toolsDesc: 'Synastrie, relocalisation et prévision des transits.',
    chineseShort: 'Chinois',
    fiveElements: 'Cinq éléments',
    numerologyShort: 'Code Numérique',
    soulVibrationShort: 'Vibration de l\'âme',
    tarotSynthesis: 'Synthèse du Tarot',
    tarotSynthesisDesc: 'Interrogez l\'oracle et déchiffrez le miroir de l\'âme.',
    sunNow: 'Soleil en ce moment',
    cosmicBalance: 'Équilibre Cosmique',
    planetsForward: 'Les planètes avancent',
    allInnerPlanetsForward: 'Toutes les planètes intérieures avancent',
    retrogradeRevision: 'en rétrograde — temps de révision',
    forwardMotion: 'Mouvement Direct',
    unknownPhase: 'Phase inconnue',
    moonPhases: ['Nouvelle Lune','Croissant Croissant','Premier Quartier','Gibbeuse Croissante','Pleine Lune','Gibbeuse Décroissante','Dernier Quartier','Croissant Décroissant'],
    zodiacSigns: ['Bélier','Taureau','Gémeaux','Cancer','Lion','Vierge','Balance','Scorpion','Sagittaire','Capricorne','Verseau','Poissons'],
    houseThemes: {1:'Identité & Nouveau Départ',2:'Ressources & Valeurs',3:'Communication & Fratrie',4:'Foyer & Racines',5:'Créativité & Amour',6:'Santé & Travail Quotidien',7:'Partenariat & Relations',8:'Transformation & Ressources Partagées',9:'Sagesse & Voyage',10:'Carrière & Vie Publique',11:'Réseaux & Rêves',12:'Le Caché & Croissance Spirituelle'},
    chineseConnectionError: 'La connexion aux archives orientales est temporairement interrompue.',
    chineseCreditsNeeded: 'Cette analyse nécessite {n} crédits. Vous serez redirigé vers l\'archive.',
    aiGreeting: 'Bonjour! Je suis AstroMason AI — votre guide cosmique personnel. Posez-moi des questions sur votre thème, vos transits, l\'amour ou la carrière.',
    aiSubtitle: 'Guide Cosmique',
    aiPlaceholder: 'Interroger AstroMason...',
    aiNeedCredits: 'Nécessite des crédits ou un abonnement Maître',
    aiError: 'Les archives cosmiques sont temporairement indisponibles. Réessayez dans un moment.',
    numerology: {
      soulMapTitle: 'Carte Complète de l\'Âme',
      cyclesTitle: 'Roue du Temps & Défis',
      karmaAlert: 'Dette Karmique Détectée',
      coreFour: 'Les Quatre Vibrations Fondamentales'
    },
    tarot: {
      spreadOneCard: 'Carte du Jour (1 Carte)',
      spreadThreeTime: 'Le Temps (3 Cartes)',
      spreadRelationship: 'La Relation (3 Cartes)',
      spreadCelticCross: 'Croix Celtique (10 Cartes)',
      posSoulMessage: 'Message de l\'Âme',
      posPast: 'Passé', posPresent: 'Présent', posFuture: 'Futur',
      posYou: 'Vous', posOther: 'L\'Autre', posDynamic: 'La Dynamique',
      posCore: 'Le Cœur', posChallenge: 'Défi', posGoal: 'Objectif',
      posRoots: 'Racines', posSelf: 'Le Soi', posEnvironment: 'Environnement',
      posFear: 'Peur', posOutcome: 'Résultat',
      styleEsoteric: 'Ésotérique', styleEsotericDesc: 'Langage caché de l\'âme',
      stylePsychological: 'Psychologique', stylePsychologicalDesc: 'Profondeur jungienne',
      styleClassical: 'Classique', styleClassicalDesc: 'Perspicacité traditionnelle',
      noCreditsMsg: 'Vous avez 0 crédit cosmique. Voulez-vous recharger?'
    },
    landing: {
      heroTitle: 'Chronique de',
      heroSubtitle: 'Votre Âme',
      heroDesc: 'Allez au-delà des horoscopes superficiels. Astro Mason déchiffre votre âme par l\'astrologie ésotérique, le tarot profond et la numérologie sacrée.',
      startBtn: 'Commencer',
      createArchive: 'Créer votre Archive',
      login: 'Connexion',
      investmentTitle: 'Investissement Spirituel',
      investmentDesc: 'Choisissez votre voie',
      singleTitle: 'Voyage Unique',
      singlePrice: '14€',
      singleUnit: '/ rapport',
      singleDesc: 'Parfait pour approfondir votre situation actuelle.',
      singleFeatures: ['Livre de Vie complet (4000+ mots)', 'Analyse personnelle profonde', 'Accès illimité'],
      masterTitle: 'Membre Maître',
      masterPrice: '49€',
      masterUnit: '/ an',
      masterDesc: 'Accès illimité à toutes les archives, tirages et codes.',
      masterFeatures: ['Rapports Astro illimités', 'Accès total au Tarot', 'Tous les codes numérologiques', 'Hub d\'aperçus personnels'],
      bestValue: 'Meilleure Valeur',
      selectPlan: 'Choisir',
      selectMaster: 'Voie du Maître',
      authTitleLogin: 'Bon Retour',
      authTitleReg: 'Créer Profil',
      authDesc: 'Entrer dans les archives',
      emailLabel: 'E-mail',
      passLabel: 'Mot de passe',
      loginBtn: 'Se connecter',
      regBtn: 'S\'inscrire',
      noAccount: 'Pas de compte ?',
      hasAccount: 'Déjà inscrit ?',
      clickHere: 'Cliquez ici',
      forgotTitle: 'Récupérer l\'Accès',
      forgotSentMsg: 'Lien de récupération envoyé à',
      backToLogin: 'Retour à la connexion',
      demoModeNote: 'Mode démo · Connectez Supabase pour une vraie auth',
      demoNoEmail: 'Mode démo: aucun email envoyé.',
      namePlaceholder: 'Votre Nom',
      sendRecovery: 'Envoyer la Récupération',
      forgotPassword: 'Mot de passe oublié?',
      errorResetFailed: 'Impossible d\'envoyer le lien. Vérifiez l\'adresse.',
      errorAlreadyReg: 'Email déjà enregistré. Connectez-vous.',
      errorPasswordShort: 'Le mot de passe doit contenir au moins 6 caractères.',
      errorRegFailed: 'Échec de l\'inscription. Réessayez.',
      errorInvalidCred: 'Email ou mot de passe incorrect.',
      errorEmailNotConfirmed: 'Confirmez d\'abord votre email. Vérifiez votre boîte.',
      errorLoginFailed: 'Échec de la connexion. Réessayez.',
      errorGeneral: 'Une erreur s\'est produite. Réessayez.'
    }
  },
  de: {
    navDashboard: 'Dashboard',
    navProfile: 'Seelenzentrum',
    navAstrology: 'Astrologie',
    navNumerology: 'Numerologie',
    navTarot: 'Tarot',
    navHoroscope: 'Horoskop',
    navChineseAstrology: 'Chinesisch',
    navTools: 'Werkzeuge',
    navSettings: 'Einstellungen',
    navLogout: 'Abmelden',
    welcomeBack: 'Willkommen zurück im Archiv',
    soulOverview: 'Seelenübersicht',
    dailyEnergy: 'Tagesenergie',
    emotionalWave: 'Emotionale Welle',
    cosmicWeather: 'Kosmisches Wetter',
    startJourney: 'Meine Chronik starten',
    natalTitle: 'Ihr Geburtshoroskop',
    relocationTitle: 'Ortwechsel',
    transitTitle: 'Transite',
    vedicTitle: 'Vedisch',
    esotericTitle: 'Esoterisch',
    classicalTitle: 'Klassisch',
    modernTitle: 'Modern',
    writeBook: 'Mein Lebensbuch schreiben',
    archiveReport: 'Bericht archivieren',
    printReport: 'Bericht drucken',
    languageName: 'Deutsch',
    periodDay: 'Heute',
    periodWeek: 'Diese Woche',
    periodMonth: 'Diesen Monat',
    periodYear: 'Dieses Jahr',
    horoscopeTitle: 'Ihr persönliches Horoskop',
    horoscopeSubtitle: 'Basierend auf Seelentransiten',
    chineseTitle: 'Chinesisches Horoskop',
    chineseSubtitle: 'Die vier Säulen und Elemente',
    traditionLabel: 'Tradition',
    analysisLabel: 'Analyse',
    saveProfileBtn: 'Profil aktualisieren',
    saveSuccess: 'Daten erfolgreich im Seelenprofil archiviert',
    nameLabel: 'Name für Schwingung',
    birthDateLabel: 'Geburtsdatum',
    birthTimeLabel: 'Geburtszeit',
    birthLocationLabel: 'Geburtsort',
    houseSystemLabel: 'Häusersystem',
    apiKeysTitle: 'Archivschlüssel',
    apiKeysDesc: 'Diese Schlüssel öffnen tiefe KI-Analysen.',
    appearanceTitle: 'Erscheinungsbild',
    lightMode: 'Hell',
    darkMode: 'Dunkel',
    archiveTitle: 'Meine gespeicherten Einblicke',
    noArchiveDesc: 'Ihr Archiv wartet auf seine erste Geschichte...',
    readInsight: 'Einblick lesen',
    backToArchive: 'Zurück zum Archiv',
    technicalInventory: 'Technisches Inventar',
    transformationCycles: 'Transformation & Zyklen',
    powerMantraLabel: 'Ihr Kraft-Mantra',
    statusLabel: 'Status',
    loadingCoords: 'Kosmische Koordinaten werden entschlüsselt...',
    masterMemberLabel: 'Master-Mitglied',
    creditsLabel: 'Credits',
    noProfileTitle: 'Geburtsdatum und -uhrzeit fehlen',
    noProfileDesc: 'Für das Geburtshoroskop und persönliches Horoskop benötigt AstroMason genaue Informationen Ihrer Inkarnation.',
    updateProfileNow: 'Seelenprofil Jetzt Aktualisieren',
    astrologyHub: 'Astrologie Hub',
    cosmicCompass: 'Ihr kosmischer Kompass',
    tabChart: 'Karte',
    tabHoroscope: 'Horoskop',
    tabLifeBook: 'Lebensbuch',
    tabSolarReturn: 'Sonnenrückkehr',
    tabProgression: 'Progressionen',
    tabCalendar: 'Kalender',
    planetaryPositions: 'Planetarische Positionen',
    annualProfections: 'Jährliche Profektionen',
    ageLabel: 'Alter',
    traditionalLabel: 'Traditionell',
    houseLabel: 'Haus',
    yearLord: 'Jahresherr',
    profectedSign: 'Profektiertes Zeichen',
    profectionYearDesc: 'Jedes Lebensjahr aktiviert ein neues Haus. Dies ist die kosmische Energie Ihres nächsten Lebensjahres.',
    soulChronicle: 'Die Chronik Ihrer Seele',
    soulChronicleDesc: 'Eine tiefe KI-Analyse mit 4000+ Wörtern, die Ihre Seele, karmische Bindungen und Ihr volles Potenzial entschlüsselt.',
    writeLifeBookNow: 'Mein Lebensbuch Jetzt Schreiben',
    priceCredits: 'Preis: 5 Credits • 4000+ Wörter',
    archivesDecoding: 'Archive werden entschlüsselt...',
    connectionError: 'Verbindung zu den tiefen Archiven derzeit nicht möglich.',
    generatingReport: 'AstroMason entschlüsselt Ihre Seele...',
    sunTodayLabel: 'Sonne Heute',
    sunVitality: 'Ihre Lebenskraft und äußere Identität',
    moonLabel: 'Mond',
    emotionalFlow: 'Emotionale Strömung gerade jetzt',
    dailyTarotCard: 'Tages-Tarot-Karte',
    numerologyCycles: 'Numerologie-Zyklen',
    personalYearLabel: 'Persönliches Jahr',
    personalMonthLabel: 'Persönlicher Monat',
    numerologyNowDesc: 'Numerologische Energie jetzt — klicken für Tiefenanalyse',
    activeTransitsNow: 'Aktive Transite Gerade Jetzt',
    seeChartArrow: 'Karte sehen →',
    astrologicalAnalysis: 'Astrologische Analyse',
    astrologicalAnalysisDesc: 'Tauchen Sie tief in Ihr Geburtshoroskop ein, prüfen Sie Ihre Beziehungssynergie oder sehen Sie Ihre kommenden Transite.',
    openStarMap: 'Sternenkarte Öffnen',
    personalHoroscopeShort: 'Ihr Persönliches Horoskop',
    personalHoroscopeDesc: 'Tag, Woche, Monat oder Jahr — basierend auf Ihrem Geburtshoroskop.',
    coupleHoroscope: 'Paar-Horoskop & Werkzeuge',
    toolsDesc: 'Synastrie, Ortswechsel und wöchentliche Transitprognose.',
    chineseShort: 'Chinesisch',
    fiveElements: 'Fünf Elemente',
    numerologyShort: 'Zahlencode',
    soulVibrationShort: 'Seelenschwingung',
    tarotSynthesis: 'Tarot-Synthese',
    tarotSynthesisDesc: 'Befragen Sie das Orakel und entschlüsseln Sie den Spiegel der Seele.',
    sunNow: 'Sonne gerade jetzt',
    cosmicBalance: 'Kosmisches Gleichgewicht',
    planetsForward: 'Planeten bewegen sich vorwärts',
    allInnerPlanetsForward: 'Alle inneren Planeten bewegen sich vorwärts',
    retrogradeRevision: 'bewegt sich rückwärts — Zeit zur Überarbeitung',
    forwardMotion: 'Direktbewegung',
    unknownPhase: 'Unbekannte Phase',
    moonPhases: ['Neumond','Zunehmende Sichel','Erstes Viertel','Zunehmender Mond','Vollmond','Abnehmender Mond','Letztes Viertel','Abnehmende Sichel'],
    zodiacSigns: ['Widder','Stier','Zwillinge','Krebs','Löwe','Jungfrau','Waage','Skorpion','Schütze','Steinbock','Wassermann','Fische'],
    houseThemes: {1:'Identität & Neubeginn',2:'Ressourcen & Werte',3:'Kommunikation & Geschwister',4:'Heimat & Wurzeln',5:'Kreativität & Liebe',6:'Gesundheit & Tagesarbeit',7:'Partnerschaft & Beziehungen',8:'Transformation & Geteilte Ressourcen',9:'Weisheit & Reise',10:'Karriere & Öffentliches Leben',11:'Netzwerke & Träume',12:'Das Verborgene & Spirituelles Wachstum'},
    chineseConnectionError: 'Die Verbindung zu den östlichen Archiven ist vorübergehend unterbrochen.',
    chineseCreditsNeeded: 'Diese Analyse erfordert {n} Credits. Sie werden jetzt zum Archiv weitergeleitet.',
    aiGreeting: 'Hallo! Ich bin AstroMason AI — Ihr persönlicher kosmischer Berater. Fragen Sie mich nach Ihrem Horoskop, Transiten, Liebe oder Karriere.',
    aiSubtitle: 'Kosmischer Berater',
    aiPlaceholder: 'AstroMason befragen...',
    aiNeedCredits: 'Erfordert Credits oder Master-Abonnement',
    aiError: 'Die kosmischen Archive sind vorübergehend nicht verfügbar. Bitte versuchen Sie es erneut.',
    numerology: {
      soulMapTitle: 'Vollständige Seelenkarte',
      cyclesTitle: 'Rad der Zeit & Herausforderungen',
      karmaAlert: 'Karmische Schuld Erkannt',
      coreFour: 'Die Vier Kernschwingungen'
    },
    tarot: {
      spreadOneCard: 'Tageskarte (1 Karte)',
      spreadThreeTime: 'Die Zeit (3 Karten)',
      spreadRelationship: 'Die Beziehung (3 Karten)',
      spreadCelticCross: 'Keltisches Kreuz (10 Karten)',
      posSoulMessage: 'Botschaft der Seele',
      posPast: 'Vergangenheit', posPresent: 'Gegenwart', posFuture: 'Zukunft',
      posYou: 'Sie', posOther: 'Der Andere', posDynamic: 'Die Dynamik',
      posCore: 'Der Kern', posChallenge: 'Herausforderung', posGoal: 'Ziel',
      posRoots: 'Wurzeln', posSelf: 'Das Selbst', posEnvironment: 'Umgebung',
      posFear: 'Angst', posOutcome: 'Ergebnis',
      styleEsoteric: 'Esoterisch', styleEsotericDesc: 'Verborgene Sprache der Seele',
      stylePsychological: 'Psychologisch', stylePsychologicalDesc: 'Jungianische Tiefe',
      styleClassical: 'Klassisch', styleClassicalDesc: 'Traditionelle Einsicht',
      noCreditsMsg: 'Sie haben 0 kosmische Credits. Möchten Sie aufladen?'
    },
    landing: {
      heroTitle: 'Chronik',
      heroSubtitle: 'Ihrer Seele',
      heroDesc: 'Gehen Sie über oberflächliche Horoskope hinaus. Astro Mason entschlüsselt Ihre Seele durch esoterische Astrologie, tiefes Tarot und heilige Numerologie.',
      startBtn: 'Reise beginnen',
      createArchive: 'Archiv erstellen',
      login: 'Login',
      investmentTitle: 'Seeleninvestition',
      investmentDesc: 'Wählen Sie Ihren Weg zur Selbsterkenntnis',
      singleTitle: 'Einzelreise',
      singlePrice: '14€',
      singleUnit: '/ Bericht',
      singleDesc: 'Perfekt für einen tiefen Einblick in Ihre aktuelle Situation.',
      singleFeatures: ['Vollständiges "Lebensbuch" (4000+ Wörter)', 'Tiefe persönliche Analyse', 'Ewiger Zugriff'],
      masterTitle: 'Master-Mitgliedschaft',
      masterPrice: '49€',
      masterUnit: '/ Jahr',
      masterDesc: 'Unbegrenzter Zugriff auf alle Archive, Tarot-Legungen und Codes.',
      masterFeatures: ['Unbegrenzte Berichte', 'Voller Tarot-Zugriff', 'Alle numerologischen Codes', 'Persönlicher Insight-Hub'],
      bestValue: 'Bester Wert',
      selectPlan: 'Plan wählen',
      selectMaster: 'Weg des Meisters',
      authTitleLogin: 'Willkommen zurück',
      authTitleReg: 'Profil erstellen',
      authDesc: 'Betreten Sie die tiefen Archive',
      emailLabel: 'E-Mail-Adresse',
      passLabel: 'Passord',
      loginBtn: 'Einloggen',
      regBtn: 'Registrieren',
      noAccount: 'Kein Konto?',
      hasAccount: 'Bereits ein Konto?',
      clickHere: 'Hier klicken',
      forgotTitle: 'Zugang Wiederherstellen',
      forgotSentMsg: 'Wiederherstellungslink gesendet an',
      backToLogin: 'Zurück zur Anmeldung',
      demoModeNote: 'Demo-Modus · Supabase für echte Auth verbinden',
      demoNoEmail: 'Demo-Modus: keine E-Mail gesendet.',
      namePlaceholder: 'Ihr Name',
      sendRecovery: 'Wiederherstellung Senden',
      forgotPassword: 'Passwort vergessen?',
      errorResetFailed: 'Wiederherstellungslink konnte nicht gesendet werden.',
      errorAlreadyReg: 'E-Mail bereits registriert. Bitte einloggen.',
      errorPasswordShort: 'Passwort muss mindestens 6 Zeichen haben.',
      errorRegFailed: 'Registrierung fehlgeschlagen. Bitte erneut versuchen.',
      errorInvalidCred: 'Falsche E-Mail oder falsches Passwort.',
      errorEmailNotConfirmed: 'Bitte bestätigen Sie zuerst Ihre E-Mail.',
      errorLoginFailed: 'Anmeldung fehlgeschlagen. Bitte erneut versuchen.',
      errorGeneral: 'Etwas ist schiefgelaufen. Bitte erneut versuchen.'
    }
  },
  ru: {
    navDashboard: 'Панель',
    navProfile: 'Центр Души',
    navAstrology: 'Астрология',
    navNumerology: 'Нумерология',
    navTarot: 'Таро',
    navHoroscope: 'Гороскоп',
    navChineseAstrology: 'Китайский',
    navTools: 'Инструменты',
    navSettings: 'Настройки',
    navLogout: 'Выйти',
    welcomeBack: 'Добро пожаловать в архивы',
    soulOverview: 'Обзор Души',
    dailyEnergy: 'Энергия Дня',
    emotionalWave: 'Эмоциональная Волна',
    cosmicWeather: 'Космическая Погода',
    startJourney: 'Начать Хронику',
    natalTitle: 'Натальная Карта',
    relocationTitle: 'Релокация',
    transitTitle: 'Транзиты',
    vedicTitle: 'Ведическая',
    esotericTitle: 'Эзотерическая',
    classicalTitle: 'Классическая',
    modernTitle: 'Модерн',
    writeBook: 'Написать Книга Жизни',
    archiveReport: 'Архивировать Отчет',
    printReport: 'Печать Отчета',
    languageName: 'Русский',
    periodDay: 'Сегодня',
    periodWeek: 'Эта неделя',
    periodMonth: 'Этот месяц',
    periodYear: 'Этот год',
    horoscopeTitle: 'Личный Гороскоп',
    horoscopeSubtitle: 'На основе транзитов души',
    chineseTitle: 'Китайский Гороскоп',
    chineseSubtitle: 'Четыре столпа и баланс стихий',
    traditionLabel: 'Традиция',
    analysisLabel: 'Анализ',
    saveProfileBtn: 'Обновить Профиль',
    saveSuccess: 'Данные успешно заархивированы',
    nameLabel: 'Имя для вибрации',
    birthDateLabel: 'Дата рождения',
    birthTimeLabel: 'Время рождения',
    birthLocationLabel: 'Место рождения',
    houseSystemLabel: 'Система домов',
    apiKeysTitle: 'Ключи доступа',
    apiKeysDesc: 'Эти ключи открывают глубокий анализ ИИ.',
    appearanceTitle: 'Внешний вид',
    lightMode: 'Светлая',
    darkMode: 'Темная',
    archiveTitle: 'Сохраненные идеи',
    noArchiveDesc: 'Ваш архив ждет своей первой истории...',
    readInsight: 'Читать',
    backToArchive: 'Назад в Архив',
    technicalInventory: 'Технический Инвентарь',
    transformationCycles: 'Трансформация и Циклы',
    powerMantraLabel: 'Мантра Силы',
    statusLabel: 'Статус',
    loadingCoords: 'Расшифровка космических координат...',
    masterMemberLabel: 'Мастер-Подписка',
    creditsLabel: 'Кредиты',
    noProfileTitle: 'Дата и время рождения отсутствуют',
    noProfileDesc: 'Для просмотра натальной карты AstroMason нужна точная информация о вашем воплощении.',
    updateProfileNow: 'Обновить Профиль Сейчас',
    astrologyHub: 'Астрологический Хаб',
    cosmicCompass: 'Ваш космический компас',
    tabChart: 'Карта',
    tabHoroscope: 'Гороскоп',
    tabLifeBook: 'Книга Жизни',
    tabSolarReturn: 'Соляр',
    tabProgression: 'Прогрессии',
    tabCalendar: 'Календарь',
    planetaryPositions: 'Планетарные Позиции',
    annualProfections: 'Годовые Профекции',
    ageLabel: 'Возраст',
    traditionalLabel: 'Традиционный',
    houseLabel: 'Дом',
    yearLord: 'Владыка Года',
    profectedSign: 'Профецированный Знак',
    profectionYearDesc: 'Каждый год жизни активирует новый дом. Это космическая энергия вашего следующего года жизни.',
    soulChronicle: 'Хроника Вашей Души',
    soulChronicleDesc: 'Глубокий анализ ИИ на 4000+ слов, расшифровывающий вашу душу, кармические связи и полный потенциал.',
    writeLifeBookNow: 'Написать Мою Книгу Жизни',
    priceCredits: 'Цена: 5 Кредитов • 4000+ Слов',
    archivesDecoding: 'Расшифровка архивов...',
    connectionError: 'Не удалось подключиться к глубоким архивам.',
    generatingReport: 'AstroMason расшифровывает вашу душу...',
    sunTodayLabel: 'Солнце Сегодня',
    sunVitality: 'Ваша жизненная сила и внешняя идентичность',
    moonLabel: 'Луна',
    emotionalFlow: 'Эмоциональный поток прямо сейчас',
    dailyTarotCard: 'Карта Таро Дня',
    numerologyCycles: 'Нумерологические Циклы',
    personalYearLabel: 'Личный Год',
    personalMonthLabel: 'Личный Месяц',
    numerologyNowDesc: 'Нумерологическая энергия сейчас — нажмите для глубокого анализа',
    activeTransitsNow: 'Активные Транзиты Прямо Сейчас',
    seeChartArrow: 'Смотреть карту →',
    astrologicalAnalysis: 'Астрологический Анализ',
    astrologicalAnalysisDesc: 'Погрузитесь в натальную карту, проверьте синастрию или посмотрите предстоящие транзиты.',
    openStarMap: 'Открыть Звёздную Карту',
    personalHoroscopeShort: 'Ваш Личный Гороскоп',
    personalHoroscopeDesc: 'День, неделя, месяц или год — на основе натальной карты.',
    coupleHoroscope: 'Гороскоп Пары & Инструменты',
    toolsDesc: 'Синастрия, релокация и еженедельный прогноз транзитов.',
    chineseShort: 'Китайский',
    fiveElements: 'Пять элементов',
    numerologyShort: 'Числовой Код',
    soulVibrationShort: 'Вибрация души',
    tarotSynthesis: 'Синтез Таро',
    tarotSynthesisDesc: 'Вопросите оракула и расшифруйте зеркало души.',
    sunNow: 'Солнце прямо сейчас',
    cosmicBalance: 'Космический Баланс',
    planetsForward: 'Планеты движутся вперёд',
    allInnerPlanetsForward: 'Все внутренние планеты движутся вперёд',
    retrogradeRevision: 'движется ретроградно — время пересмотра',
    forwardMotion: 'Прямое Движение',
    unknownPhase: 'Неизвестная фаза',
    moonPhases: ['Новолуние','Растущий Серп','Первая Четверть','Растущая Луна','Полнолуние','Убывающая Луна','Последняя Четверть','Убывающий Серп'],
    zodiacSigns: ['Овен','Телец','Близнецы','Рак','Лев','Дева','Весы','Скорпион','Стрелец','Козерог','Водолей','Рыбы'],
    houseThemes: {1:'Идентичность & Новое Начало',2:'Ресурсы & Ценности',3:'Коммуникация & Братья',4:'Дом & Корни',5:'Творчество & Любовь',6:'Здоровье & Ежедневная Работа',7:'Партнёрство & Отношения',8:'Трансформация & Общие Ресурсы',9:'Мудрость & Путешествие',10:'Карьера & Публичная Жизнь',11:'Сети & Мечты',12:'Скрытое & Духовный Рост'},
    chineseConnectionError: 'Соединение с восточными архивами временно нарушено.',
    chineseCreditsNeeded: 'Этот анализ требует {n} кредитов. Вы будете перенаправлены в архив.',
    aiGreeting: 'Привет! Я AstroMason AI — ваш личный космический проводник. Задайте вопросы о карте, транзитах, любви или карьере.',
    aiSubtitle: 'Космический Проводник',
    aiPlaceholder: 'Спросить AstroMason...',
    aiNeedCredits: 'Требуются кредиты или подписка Мастер',
    aiError: 'Космические архивы временно недоступны. Попробуйте через мгновение.',
    numerology: {
      soulMapTitle: 'Полная Карта Души',
      cyclesTitle: 'Колесо Времени & Испытания',
      karmaAlert: 'Кармический Долг Обнаружен',
      coreFour: 'Четыре Основных Вибрации'
    },
    tarot: {
      spreadOneCard: 'Карта Дня (1 Карта)',
      spreadThreeTime: 'Время (3 Карты)',
      spreadRelationship: 'Отношения (3 Карты)',
      spreadCelticCross: 'Кельтский Крест (10 Карт)',
      posSoulMessage: 'Послание Души',
      posPast: 'Прошлое', posPresent: 'Настоящее', posFuture: 'Будущее',
      posYou: 'Вы', posOther: 'Другой', posDynamic: 'Динамика',
      posCore: 'Суть', posChallenge: 'Вызов', posGoal: 'Цель',
      posRoots: 'Корни', posSelf: 'Я', posEnvironment: 'Окружение',
      posFear: 'Страх', posOutcome: 'Исход',
      styleEsoteric: 'Эзотерический', styleEsotericDesc: 'Скрытый язык души',
      stylePsychological: 'Психологический', stylePsychologicalDesc: 'Юнгианская глубина',
      styleClassical: 'Классический', styleClassicalDesc: 'Традиционная мудрость',
      noCreditsMsg: 'У вас 0 космических кредитов. Хотите пополнить?'
    },
    landing: {
      heroTitle: 'Хроника',
      heroSubtitle: 'Вашей Души',
      heroDesc: 'За пределами поверхностных гороскопов. Astro Mason расшифровывает вашу душу через астрологию, таро и нумерологию.',
      startBtn: 'Начать Путь',
      createArchive: 'Создать Архив',
      login: 'Войти',
      investmentTitle: 'Инвестиция в себя',
      investmentDesc: 'Выберите свой путь к познанию',
      singleTitle: 'Разовый отчет',
      singlePrice: '14€',
      singleUnit: '/ отчет',
      singleDesc: 'Идеально для глубокого погружения в текущую ситуацию.',
      singleFeatures: ['Полная "Книга Жизни" (4000+ слов)', 'Глубокий личный анализ', 'Вечный доступ'],
      masterTitle: 'Мастер-подписка',
      masterPrice: '49€',
      masterUnit: '/ год',
      masterDesc: 'Полный и неограниченный доступ ко всем архивам и кодам.',
      masterFeatures: ['Безлимитные отчеты', 'Полный доступ к Таро', 'Все нумерологические коды', 'Личный хаб озарений'],
      bestValue: 'Лучший выбор',
      selectPlan: 'Выбрать',
      selectMaster: 'Путь Мастера',
      authTitleLogin: 'С возвращением',
      authTitleReg: 'Создать профиль',
      authDesc: 'Войти в глубокие архивы',
      emailLabel: 'E-mail адрес',
      passLabel: 'Пароль',
      loginBtn: 'Войти',
      regBtn: 'Регистрация',
      noAccount: 'Нет аккаунта?',
      hasAccount: 'Уже есть аккаунт?',
      clickHere: 'Нажмите сюда',
      forgotTitle: 'Восстановить Доступ',
      forgotSentMsg: 'Ссылка восстановления отправлена на',
      backToLogin: 'Назад ко входу',
      demoModeNote: 'Демо-режим · Подключите Supabase для реальной авторизации',
      demoNoEmail: 'Демо-режим: письмо не отправлено.',
      namePlaceholder: 'Ваше Имя',
      sendRecovery: 'Отправить Восстановление',
      forgotPassword: 'Забыли пароль?',
      errorResetFailed: 'Не удалось отправить ссылку восстановления.',
      errorAlreadyReg: 'Email уже зарегистрирован. Войдите.',
      errorPasswordShort: 'Пароль должен содержать не менее 6 символов.',
      errorRegFailed: 'Регистрация не удалась. Попробуйте ещё раз.',
      errorInvalidCred: 'Неверный email или пароль.',
      errorEmailNotConfirmed: 'Сначала подтвердите email. Проверьте почту.',
      errorLoginFailed: 'Вход не удался. Попробуйте ещё раз.',
      errorGeneral: 'Что-то пошло не так. Попробуйте ещё раз.'
    }
  }
};

export const ASTRO_KNOWLEDGE_BASE: Record<string, string> = {
    'Væren': 'Keiseren (Struktur, lederskap, initiativ)',
    'Tyren': 'Hierofanten (Tradisjon, verdier, stabilitet)',
    'Tvillingene': 'De Elskende (Valg, dualitet, kommunikasjon)',
    'Krepsen': 'Vognen (Beskyttelse, vilje, emosjonell kontroll)',
    'Løven': 'Styrke (Indre kraft, mot, lidenskap)',
    'Jomfruen': 'Eneboeren (Analyse, introspeksjon, detaljer)',
    'Vekten': 'Rettferdighet (Balanse, karma, sannhet)',
    'Skorpionen': 'Døden (Transformasjon, slippe taket, fornyelse)',
    'Skytten': 'Måtehold (Syntese, visjon, høyere mening)',
    'Steinbukken': 'Djevelen (Materialisme, ambisjon, grenser)',
    'Vannmannen': 'Stjernen (Håp, humanitær visjon, fremtid)',
    'Fiskene': 'Månen (Illusjon, drømmer, underbevissthet)',
    'Ild': 'Inspirasjon, handling, vilje (Wands)',
    'Jord': 'Manifestasjon, krop, ressurser (Pentacles)',
    'Luft': 'Tanke, kommunikasjon, konflikt (Swords)',
    'Vann': 'Følelser, relasjoner, intuisjon (Cups)'
};

// Fixes for Library, Methodology, Courses, and Tarot components
export const METHODOLOGY_DESCRIPTIONS: Record<MethodologyType, string> = {
  [MethodologyType.WESTERN_CLASSICAL]: "Tradisjonell vestlig astrologi med fokus på essensielle verdigheter og hussystemer.",
  [MethodologyType.HELLENISTIC]: "Antikk gresk astrologi som gjenoppdaget teknikker som sekt og tidsherrer.",
  [MethodologyType.VEDIC]: "Indisk astrologi (Jyotish) basert på det sideriske dyrekretsen og nakshatras.",
  [MethodologyType.PSYCHOLOGICAL]: "Moderne tilnærming som bruker astrologi som et verktøy for selvutvikling og forståelse av psyken.",
  [MethodologyType.EVOLUTIONARY]: "Fokus på sjelens reise gjennom livstider, ofte med fokus på Pluto og månens noder.",
  [MethodologyType.ESOTERIC]: "Sjelens astrologi slik den er presentert av Alice Bailey, med fokus på sjelens formål.",
  [MethodologyType.SPECIALIZED]: "Spesialiserte teknikker som horær, eleksjonell eller medisinsk astrologi."
};

export const AUTHORS: Author[] = [
  {
    id: '1',
    name: 'Claudius Ptolemy',
    era: 'Ancient',
    specialty: 'Classical Foundations',
    description: 'Forfatter av Tetrabiblos, fundamentet for vestlig astrologi.',
    keyWorks: ['Tetrabiblos', 'Almagest'],
    methodologies: [MethodologyType.WESTERN_CLASSICAL]
  },
  {
    id: '2',
    name: 'Vettius Valens',
    era: 'Ancient',
    specialty: 'Hellenistic Techniques',
    description: 'En av de mest praktiske kildene for antikke astrologiske teknikker.',
    keyWorks: ['The Anthology'],
    methodologies: [MethodologyType.HELLENISTIC]
  },
  {
    id: '3',
    name: 'Alan Leo',
    era: 'Modern',
    specialty: 'Psychological Astrology',
    description: 'Ofte kalt faren til moderne astrologi.',
    keyWorks: ['Astrology for All'],
    methodologies: [MethodologyType.PSYCHOLOGICAL]
  }
];

export const RESOURCES: Resource[] = [
  {
    id: 'r1',
    title: 'Christian Astrology',
    author: 'William Lilly',
    type: 'Book',
    description: 'Den definitive guiden til horær astrologi.',
    isRecommended: true,
    link: 'https://archive.org'
  }
];

export const COURSES: Course[] = [
  {
    id: 'c1',
    title: 'Introduksjon til Klassisk Astrologi',
    description: 'Lær de grunnleggende prinsippene i vestlig tradisjon.',
    level: 'Beginner',
    duration: '10 timer',
    instructor: 'AstroMason',
    thumbnail: 'https://images.unsplash.com/photo-1532667449560-72a95c8d381b',
    progress: 0,
    isCertified: true,
    modules: []
  },
  {
    id: 'c2',
    title: 'Esoterisk Visdom',
    description: 'Utforsk sjelens vei gjennom stjernene.',
    level: 'Advanced',
    duration: '20 timer',
    instructor: 'AstroMason',
    thumbnail: 'https://images.unsplash.com/photo-1518133910546-b6c2fb7d79e3',
    progress: 0,
    isCertified: true,
    modules: []
  }
];

export const MAJOR_ARCANA = [
  { id: 0,  name: 'Narren',              img: 'https://upload.wikimedia.org/wikipedia/commons/9/90/RWS_Tarot_00_Fool.jpg',               keywords: ['Start', 'Uskyld', 'Risiko'] },
  { id: 1,  name: 'Magikeren',           img: 'https://upload.wikimedia.org/wikipedia/commons/d/de/RWS_Tarot_01_Magician.jpg',           keywords: ['Manifestasjon', 'Kraft', 'Vilje'] },
  { id: 2,  name: 'Yppersteprestinnen', img: 'https://upload.wikimedia.org/wikipedia/commons/8/88/RWS_Tarot_02_High_Priestess.jpg',     keywords: ['Intuisjon', 'Mysterier', 'Underbevissthet'] },
  { id: 3,  name: 'Keiserinnen',         img: 'https://upload.wikimedia.org/wikipedia/commons/d/d2/RWS_Tarot_03_Empress.jpg',            keywords: ['Fruktbarhet', 'Natur', 'Overflod'] },
  { id: 4,  name: 'Keiseren',            img: 'https://upload.wikimedia.org/wikipedia/commons/c/c3/RWS_Tarot_04_Emperor.jpg',            keywords: ['Autoritet', 'Struktur', 'Stabilitet'] },
  { id: 5,  name: 'Ypperstepresten',     img: 'https://upload.wikimedia.org/wikipedia/commons/8/8d/RWS_Tarot_05_Hierophant.jpg',         keywords: ['Tradisjon', 'Spiritualitet', 'Veiledning'] },
  { id: 6,  name: 'Elskerne',            img: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/TheLovers.jpg',                       keywords: ['Kjærlighet', 'Valg', 'Union'] },
  { id: 7,  name: 'Vognen',              img: 'https://upload.wikimedia.org/wikipedia/commons/9/9b/RWS_Tarot_07_Chariot.jpg',            keywords: ['Seier', 'Kontroll', 'Besluttsomhet'] },
  { id: 8,  name: 'Styrken',             img: 'https://upload.wikimedia.org/wikipedia/commons/f/f5/RWS_Tarot_08_Strength.jpg',           keywords: ['Mot', 'Tålmodighet', 'Indre kraft'] },
  { id: 9,  name: 'Eremiten',            img: 'https://upload.wikimedia.org/wikipedia/commons/4/4d/RWS_Tarot_09_Hermit.jpg',             keywords: ['Introspeksjon', 'Søken', 'Visdom'] },
  { id: 10, name: 'Lykkens Hjul',        img: 'https://upload.wikimedia.org/wikipedia/commons/3/3c/RWS_Tarot_10_Wheel_of_Fortune.jpg',   keywords: ['Syklus', 'Karma', 'Skjebne'] },
  { id: 11, name: 'Rettferdigheten',     img: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/RWS_Tarot_11_Justice.jpg',            keywords: ['Balanse', 'Sannhet', 'Årsak-virkning'] },
  { id: 12, name: 'Den Hengte',          img: 'https://upload.wikimedia.org/wikipedia/commons/2/2b/RWS_Tarot_12_Hanged_Man.jpg',         keywords: ['Overgivelse', 'Pause', 'Nytt perspektiv'] },
  { id: 13, name: 'Døden',              img: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/RWS_Tarot_13_Death.jpg',              keywords: ['Transformasjon', 'Slutt', 'Ny begynnelse'] },
  { id: 14, name: 'Temperansen',         img: 'https://upload.wikimedia.org/wikipedia/commons/f/f8/RWS_Tarot_14_Temperance.jpg',         keywords: ['Balanse', 'Moderasjon', 'Flyt'] },
  { id: 15, name: 'Djevelen',            img: 'https://upload.wikimedia.org/wikipedia/commons/5/55/RWS_Tarot_15_Devil.jpg',              keywords: ['Binding', 'Skygge', 'Materiell fristelse'] },
  { id: 16, name: 'Tårnet',              img: 'https://upload.wikimedia.org/wikipedia/commons/5/53/RWS_Tarot_16_Tower.jpg',              keywords: ['Kaos', 'Åpenbaring', 'Brudd'] },
  { id: 17, name: 'Stjernen',            img: 'https://upload.wikimedia.org/wikipedia/commons/d/db/RWS_Tarot_17_Star.jpg',               keywords: ['Håp', 'Inspirasjon', 'Fornyelse'] },
  { id: 18, name: 'Månen',               img: 'https://upload.wikimedia.org/wikipedia/commons/7/7f/RWS_Tarot_18_Moon.jpg',               keywords: ['Illusjon', 'Underbevissthet', 'Frykt'] },
  { id: 19, name: 'Solen',               img: 'https://upload.wikimedia.org/wikipedia/commons/1/17/RWS_Tarot_19_Sun.jpg',                keywords: ['Glede', 'Suksess', 'Vitalitet'] },
  { id: 20, name: 'Dommen',              img: 'https://upload.wikimedia.org/wikipedia/commons/d/dd/RWS_Tarot_20_Judgement.jpg',          keywords: ['Oppvåkning', 'Tilgivelse', 'Transformasjon'] },
  { id: 21, name: 'Verden',              img: 'https://upload.wikimedia.org/wikipedia/commons/f/ff/RWS_Tarot_21_World.jpg',              keywords: ['Fullendelse', 'Integrering', 'Triumf'] },
];

// Helper to build Wikimedia Commons Special:FilePath URL (follows redirect, no hash needed)
const wmc = (file: string) => `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(file)}`;

export const MINOR_ARCANA = [
  // ── STAVER (Wands) – Ild / Handling / Kreativitet ──────────────────────────
  { id: 100, suit: 'staver', name: 'Es av Staver',       img: wmc('Wands01.jpg'), keywords: ['Nytt initiativ', 'Kreativ kraft', 'Gnist'] },
  { id: 101, suit: 'staver', name: '2 av Staver',        img: wmc('Wands02.jpg'), keywords: ['Planlegging', 'Fremtidsvision', 'Personlig makt'] },
  { id: 102, suit: 'staver', name: '3 av Staver',        img: wmc('Wands03.jpg'), keywords: ['Ekspansjon', 'Framsyn', 'Reise'] },
  { id: 103, suit: 'staver', name: '4 av Staver',        img: wmc('Wands04.jpg'), keywords: ['Feiring', 'Harmoni', 'Hjemkomst'] },
  { id: 104, suit: 'staver', name: '5 av Staver',        img: wmc('Wands05.jpg'), keywords: ['Konflikt', 'Konkurranse', 'Kaos'] },
  { id: 105, suit: 'staver', name: '6 av Staver',        img: wmc('Wands06.jpg'), keywords: ['Seier', 'Anerkjennelse', 'Suksess'] },
  { id: 106, suit: 'staver', name: '7 av Staver',        img: wmc('Wands07.jpg'), keywords: ['Forsvar', 'Utholdenhet', 'Utfordring'] },
  { id: 107, suit: 'staver', name: '8 av Staver',        img: wmc('Wands08.jpg'), keywords: ['Rask bevegelse', 'Kommunikasjon', 'Fart'] },
  { id: 108, suit: 'staver', name: '9 av Staver',        img: wmc('Wands09.jpg'), keywords: ['Motstandskraft', 'Grenser', 'Utmattelse'] },
  { id: 109, suit: 'staver', name: '10 av Staver',       img: wmc('Wands10.jpg'), keywords: ['Byrde', 'Ansvar', 'Overbelastning'] },
  { id: 110, suit: 'staver', name: 'Knekt av Staver',    img: wmc('Wands11.jpg'), keywords: ['Entusiasme', 'Nysgjerrighet', 'Eventyr'] },
  { id: 111, suit: 'staver', name: 'Ridder av Staver',   img: wmc('Wands12.jpg'), keywords: ['Lidenskap', 'Impulsivitet', 'Handling'] },
  { id: 112, suit: 'staver', name: 'Dronning av Staver', img: wmc('Wands13.jpg'), keywords: ['Karisma', 'Selvtillit', 'Vitalitet'] },
  { id: 113, suit: 'staver', name: 'Konge av Staver',    img: wmc('Wands14.jpg'), keywords: ['Visjonær leder', 'Inspirasjon', 'Modig autoritet'] },

  // ── BEGER (Cups) – Vann / Følelser / Relasjoner ────────────────────────────
  { id: 200, suit: 'beger', name: 'Es av Beger',         img: wmc('Cups01.jpg'), keywords: ['Ny kjærlighet', 'Emosjonell åpning', 'Intuitiv gave'] },
  { id: 201, suit: 'beger', name: '2 av Beger',          img: wmc('Cups02.jpg'), keywords: ['Partnerskap', 'Gjensidighet', 'Tiltrekning'] },
  { id: 202, suit: 'beger', name: '3 av Beger',          img: wmc('Cups03.jpg'), keywords: ['Feiring', 'Vennskap', 'Fellesskap'] },
  { id: 203, suit: 'beger', name: '4 av Beger',          img: wmc('Cups04.jpg'), keywords: ['Apati', 'Kontemplasjon', 'Savnet mulighet'] },
  { id: 204, suit: 'beger', name: '5 av Beger',          img: wmc('Cups05.jpg'), keywords: ['Sorg', 'Tap', 'Skuffelse'] },
  { id: 205, suit: 'beger', name: '6 av Beger',          img: wmc('Cups06.jpg'), keywords: ['Nostalgi', 'Barndom', 'Uskyld'] },
  { id: 206, suit: 'beger', name: '7 av Beger',          img: wmc('Cups07.jpg'), keywords: ['Illusjoner', 'Fantasier', 'Valg'] },
  { id: 207, suit: 'beger', name: '8 av Beger',          img: wmc('Cups08.jpg'), keywords: ['Forlate', 'Søken', 'Desillusjonering'] },
  { id: 208, suit: 'beger', name: '9 av Beger',          img: wmc('Cups09.jpg'), keywords: ['Ønskeoppfyllelse', 'Tilfredshet', 'Lykke'] },
  { id: 209, suit: 'beger', name: '10 av Beger',         img: wmc('Cups10.jpg'), keywords: ['Harmoni', 'Familie', 'Emosjonell fullendelse'] },
  { id: 210, suit: 'beger', name: 'Knekt av Beger',      img: wmc('Cups11.jpg'), keywords: ['Drømmende', 'Empatisk', 'Kreativt budskap'] },
  { id: 211, suit: 'beger', name: 'Ridder av Beger',     img: wmc('Cups12.jpg'), keywords: ['Romantikk', 'Idealist', 'Sjarmerende'] },
  { id: 212, suit: 'beger', name: 'Dronning av Beger',   img: wmc('Cups13.jpg'), keywords: ['Intuisjon', 'Medfølelse', 'Emosjonell visdom'] },
  { id: 213, suit: 'beger', name: 'Konge av Beger',      img: wmc('Cups14.jpg'), keywords: ['Emosjonell modenhet', 'Balansert følelser', 'Omsorgsfull leder'] },

  // ── SVERD (Swords) – Luft / Intellekt / Utfordringer ──────────────────────
  { id: 300, suit: 'sverd', name: 'Es av Sverd',         img: wmc('Swords01.jpg'), keywords: ['Klarhet', 'Sannhet', 'Mental kraft'] },
  { id: 301, suit: 'sverd', name: '2 av Sverd',          img: wmc('Swords02.jpg'), keywords: ['Fastlåst', 'Unngåelse', 'Vanskelig valg'] },
  { id: 302, suit: 'sverd', name: '3 av Sverd',          img: wmc('Swords03.jpg'), keywords: ['Hjertesorg', 'Smerte', 'Svik'] },
  { id: 303, suit: 'sverd', name: '4 av Sverd',          img: wmc('Swords04.jpg'), keywords: ['Hvile', 'Restitusjon', 'Kontemplasjon'] },
  { id: 304, suit: 'sverd', name: '5 av Sverd',          img: wmc('Swords05.jpg'), keywords: ['Konflikt', 'Nederlag', 'Egosenter'] },
  { id: 305, suit: 'sverd', name: '6 av Sverd',          img: wmc('Swords06.jpg'), keywords: ['Overgang', 'Flukt', 'Friere farvann'] },
  { id: 306, suit: 'sverd', name: '7 av Sverd',          img: wmc('Swords07.jpg'), keywords: ['List', 'Bedrag', 'Taktikk'] },
  { id: 307, suit: 'sverd', name: '8 av Sverd',          img: wmc('Swords08.jpg'), keywords: ['Fanget', 'Begrensning', 'Selvpålagt fengsel'] },
  { id: 308, suit: 'sverd', name: '9 av Sverd',          img: wmc('Swords09.jpg'), keywords: ['Angst', 'Mareritt', 'Bekymring'] },
  { id: 309, suit: 'sverd', name: '10 av Sverd',         img: wmc('Swords10.jpg'), keywords: ['Endelig tap', 'Krise', 'Nødvendig slutt'] },
  { id: 310, suit: 'sverd', name: 'Knekt av Sverd',      img: wmc('Swords11.jpg'), keywords: ['Analytisk', 'Direkte', 'Nysgjerrig intellekt'] },
  { id: 311, suit: 'sverd', name: 'Ridder av Sverd',     img: wmc('Swords12.jpg'), keywords: ['Ambisiøs', 'Impulsiv handling', 'Intellektuell kraft'] },
  { id: 312, suit: 'sverd', name: 'Dronning av Sverd',   img: wmc('Swords13.jpg'), keywords: ['Skarpsindig', 'Uavhengig', 'Direkte kommunikasjon'] },
  { id: 313, suit: 'sverd', name: 'Konge av Sverd',      img: wmc('Swords14.jpg'), keywords: ['Intellektuell makt', 'Rettferdig dom', 'Analytisk leder'] },

  // ── PENTAKLER (Pentacles) – Jord / Det materielle / Økonomi ───────────────
  { id: 400, suit: 'pentakler', name: 'Es av Pentakler',       img: wmc('Pents01.jpg'), keywords: ['Materiell start', 'Ny mulighet', 'Overflod'] },
  { id: 401, suit: 'pentakler', name: '2 av Pentakler',        img: wmc('Pents02.jpg'), keywords: ['Balanse', 'Jonglering', 'Tilpasningsevne'] },
  { id: 402, suit: 'pentakler', name: '3 av Pentakler',        img: wmc('Pents03.jpg'), keywords: ['Samarbeid', 'Håndverk', 'Læring'] },
  { id: 403, suit: 'pentakler', name: '4 av Pentakler',        img: wmc('Pents04.jpg'), keywords: ['Gjerrighet', 'Sikkerhet', 'Kontroll'] },
  { id: 404, suit: 'pentakler', name: '5 av Pentakler',        img: wmc('Pents05.jpg'), keywords: ['Fattigdom', 'Isolasjon', 'Hardship'] },
  { id: 405, suit: 'pentakler', name: '6 av Pentakler',        img: wmc('Pents06.jpg'), keywords: ['Generøsitet', 'Veldedighet', 'Balanse i gi og ta'] },
  { id: 406, suit: 'pentakler', name: '7 av Pentakler',        img: wmc('Pents07.jpg'), keywords: ['Tålmodighet', 'Investering', 'Langsiktig vekst'] },
  { id: 407, suit: 'pentakler', name: '8 av Pentakler',        img: wmc('Pents08.jpg'), keywords: ['Flid', 'Mestring', 'Dedikert arbeid'] },
  { id: 408, suit: 'pentakler', name: '9 av Pentakler',        img: wmc('Pents09.jpg'), keywords: ['Selvforsynt', 'Luksus', 'Uavhengighet'] },
  { id: 409, suit: 'pentakler', name: '10 av Pentakler',       img: wmc('Pents10.jpg'), keywords: ['Arv', 'Familieverdi', 'Materiell fullendelse'] },
  { id: 410, suit: 'pentakler', name: 'Knekt av Pentakler',    img: wmc('Pents11.jpg'), keywords: ['Ambisiøs student', 'Pålitelig', 'Praktisk læring'] },
  { id: 411, suit: 'pentakler', name: 'Ridder av Pentakler',   img: wmc('Pents12.jpg'), keywords: ['Tålmodig', 'Metodisk', 'Hardtarbeidende'] },
  { id: 412, suit: 'pentakler', name: 'Dronning av Pentakler', img: wmc('Pents13.jpg'), keywords: ['Nærende', 'Praktisk klokskap', 'Jordnær omsorg'] },
  { id: 413, suit: 'pentakler', name: 'Konge av Pentakler',    img: wmc('Pents14.jpg'), keywords: ['Velstand', 'Forretningssans', 'Trygg autoritet'] },
];

export const FULL_TAROT_DECK = [...MAJOR_ARCANA, ...MINOR_ARCANA];
